<script type="text/javascript">

    (function() {

        var pluginElm = jQuery("[data-rcmplugininstanceid='<?= $this->instanceId ?>']");
        pluginElm.removeAttr('style');
        pluginElm.addClass('<?= $this->instanceConfig['class'] ?>');
        <?php
            if($this->instanceConfig['newLine']) {
        ?>
        pluginElm.addClass('first');
        $( "<div class='clearfix'></div>" ).insertBefore(pluginElm);
        <?php
            }
        ?>
    })();
</script>

<style type="text/css">
    .rcmPlugin.RcmActionButton .button-box {
        border: 0px solid;
        border-radius: 10px 0 10px 0;
        padding: .5em;
        width: 100%;
    }

    .rcmPlugin.RcmActionButton .button-area {
        display: table;
        min-height: 2em;
        width: 100%;
    }

    .rcmPlugin.RcmActionButton .button-content {
        display: table-cell;
        vertical-align: middle;
        horiz-align: center;
    }

    .rcmPlugin.RcmActionButton.col-md-3,
    .rcmPlugin.RcmActionButton.col-sm-12,
    .rcmPlugin.RcmActionButton.col-xs-12{
    }

    .rcmPlugin.RcmActionButton.col-md-3.first,
    .rcmPlugin.RcmActionButton.col-sm-12.first,
    .rcmPlugin.RcmActionButton.col-xs-12.first{
    }


    .rcmPlugin.RcmCallToActionBox {
        border: 1px solid #008000;
    }
</style>

<div class="button-box" style="background-color: <?= $this->instanceConfig['color'] ?>">

    <a class="button-area" href="<?= $this->escapeHtml($this->instanceConfig['href']) ?>">
        <div class="button-content">
            <?=
            $this->rcmTextEdit(
                'content',
                'My Content',
                'div',
                ['class' => 'top']
            ) ?>
        </div>
    </a>

</div>


