<?php
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-action-button/css/style.css'
);

$this->colorList = htmlentities(json_encode($this->config['rcmPlugin']['RcmActionButton']['colorSwatches']), ENT_QUOTES);
?>
<div class="button-box"
     style="background-color: <?= $this->instanceConfig['buttonColor'] ?>"
     data-button-color="<?= $this->instanceConfig['buttonColor'] ?>"
     data-link-color="<?= $this->instanceConfig['linkColor'] ?>"
     data-color-list="<?= $this->colorList ?>"
    >
    <a class="button-area" href="<?= $this->escapeHtml($this->instanceConfig['href']) ?>">
        <div class="button-content" style="color: <?= $this->instanceConfig['linkColor'] ?>">
            <?=
            $this->rcmTextEdit(
                'content',
                'My Content',
                'div',
                ['class' => 'top']
            ) ?>
        </div>
    </a>
</div>
