<?php
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-action-button/css/style.css'
);

$this->colorList = htmlentities(json_encode($this->config['rcmPlugin']['RcmActionButton']['colorSwatches']), ENT_QUOTES);
?>
<script type="text/javascript">

    (function() {

        var pluginElm = jQuery("[data-rcmplugininstanceid='<?= $this->instanceId ?>']");
        pluginElm.removeAttr('style');
        pluginElm.addClass('<?= $this->instanceConfig['class'] ?>');
        <?php
            if($this->instanceConfig['newLine'] === 'true') {
        ?>
        pluginElm.addClass('first');
        $( '<div id="RcmActionButtonClear<?= $this->instanceId ?>" class="clearfix"></div>' ).insertBefore(pluginElm);
        <?php
            }
        ?>
    })();
</script>

<div class="button-box"
     style="background-color: <?= $this->instanceConfig['buttonColor'] ?>"
     data-button-color="<?= $this->instanceConfig['buttonColor'] ?>"
     data-link-color="<?= $this->instanceConfig['linkColor'] ?>"
     data-new-line="<?= $this->instanceConfig['newLine'] ?>"
     data-color-list="<?= $this->colorList ?>"
    >

    <a class="button-area" href="<?= $this->escapeHtml($this->instanceConfig['href']) ?>">
        <div class="button-content" style="color: <?= $this->instanceConfig['linkColor'] ?>">
            <?=
            $this->rcmTextEdit(
                'content',
                'My Content',
                'div',
                ['class' => 'top']
            ) ?>
        </div>
    </a>

</div>


