<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmTwitterBootstrap\Module' => __DIR__ . '/Module.php',
    'RcmTwitterBootstrap\Factory\RcmTwitterBootstrapIncludeViewHelperFactory' =>
        __DIR__
        . '/src/RcmTwitterBootstrap/Factory/RcmTwitterBootstrapIncludeViewHelperFactory.php',
    'RcmTwitterBootstrap\View\Helper\IncludeTwitterBootstrap' => __DIR__
        . '/src/RcmTwitterBootstrap/View/Helper/IncludeTwitterBootstrap.php',
];
