<?php

/**
 * RcmLoginLink content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-login-link/style.css'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-login-link/rcm-login-link.js',
    'text/javascript'
);

echo $this->rcmJsLoginManager();
?>
<script type="text/javascript">
    $(function () {
        new RcmLoginLink(
        <?php echo $this->instanceId?>
        );
    });
</script>
<a style="<?php echo $this->isLoggedIn ? 'display:none;' : ''?>"
   class="loginLink">login</a>
<a style="<?php echo $this->isLoggedIn ? '' : 'display:none;'?>"
   class="logOutLink" href="/?logout=1">logout</a>
<div style="display:none;" class="popup">
    <form class="loginForm">
        <div class="error invalid"
             data-textEdit="errorInvalid"><?php echo $this->ic['errorInvalid']?></div>
        <div class="error missing"
             data-textEdit="errorMissing"><?php echo $this->ic['errorMissing']?></div>
        <div class="error system"
             data-textEdit="errorSystem"><?php echo $this->ic['errorSystem']?></div>


        <label for="rcmLoginLinkUserName">
            <div data-textEdit="usernameLabel"><?php echo $this->ic['usernameLabel']?></div>
        </label>
        <input class="username" type="text" value="" name="username"
               id="rcmLoginLinkUserName">
        <br>
        <label for="rcmLoginLinkPassword">
            <div data-textEdit="passwordLabel"><?php echo $this->ic['passwordLabel']?></div>
        </label>
        <input class="password" type="password" value="" name="password"
               id="rcmLoginLinkPassword">

        <div class="buttons">
            <button class="login">
                <div data-textEdit="loginButton">
                    <?php echo $this->ic['loginButton']?>
                </div>
            </button>
            <button class="processing disabled" style="display:none;"
                    class="processingButton">
                <div data-textEdit="processingButton">
                    <?php echo $this->ic['processingButton']?>
                </div>
            </button>
        </div>
    </form>
</div>