<?php

/**
 * RcmLoginLink content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-login-link/style.css'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-login-link/rcm-login-link.js',
    'text/javascript'
);

echo $this->rcmJsLoginManager();
?>
<script type="text/javascript">
    $(function () {
        new RcmLoginLink(
        <?php echo $this->instanceId?>
        );
    });
</script>
<a style="<?php echo $this->isLoggedIn ? 'display:none;' : ''?>"
   class="loginLink">
    <div data-textEdit="loginLink">
        <?php echo $this->ic['loginLink'] ?>
    </div>
</a>
<a style="<?php echo $this->isLoggedIn ? '' : 'display:none;'?>"
   class="logOutLink" href="/?logout=1">
    <div data-textEdit="logoutLink"><?php echo $this->ic['logoutLink'] ?>
    </div>
</a>
<div style="display:none;" class="popup">
    <form class="loginForm">

        <label for="rcmLoginLinkUserName" data-textEdit="usernameLabel">
            <?php echo $this->ic['usernameLabel']?>
        </label>
        <input class="username" type="text" name="username"
               id="rcmLoginLinkUserName">
        <br>
        <label for="rcmLoginLinkPassword" div data-textEdit="passwordLabel">
            <?php echo $this->ic['passwordLabel']?>
        </label>
        <input class="password" type="password" name="password"
               id="rcmLoginLinkPassword">

        <div class="buttons">
            <button class="login" data-textEdit="loginButton">
                <?php echo $this->ic['loginButton']?>
            </button>
        </div>
    </form>
</div>