<?php

/**
 * RcmLoginLink content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-login-link/style.css'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-login-link/rcm-login-link.js',
    'text/javascript'
);

echo $this->rcmJsLoginManager();
?>
<script type="text/javascript">
    $(function () {
        new RcmLoginLink(
        <?php echo $this->instanceId?>
        );
    });
</script>
<a style="<?php echo $this->isLoggedIn?'display:none;':''?>" class="logInLink">login</a>
<a style="<?php echo $this->isLoggedIn?'':'display:none;'?>" class="logOutLink" href="/?logout=1">logout</a>
<div style="display:none;" class="popup">

<!--    <div class="error" id="rcmLoginBoxInvalidError">Incorrect Username or Password</div>-->
<!--    <div cloass="error" id="rcmLoginBoxMissingError">Missing Username or Password.</div>-->
<!--    <div class="error" id="rcmLoginBoxSystemError">There was an internal problem loggin you in.  Please try back later.</div>-->
<!--    <div class="error" id="rcmLoginBoxNoAuthError">You are not authorized to view the requested page.</div>-->
<!---->
<!--    <div data-textEdit="loginErrorInvalid" class="loginError" align="center" style="display: none;">-->
<!--        Incorrect Username or Password        </div>-->

    <label for="rcmLoginLinkUserName"><div data-textEdit="username">Username or RCN:</div></label>
    <input class="usernameInput" type="text" value="" name="username" id="rcmLoginLinkUserName">
    <br>
<label for="rcmLoginLinkPassword"><div data-textEdit="password">Password:</div></label>
    <input type="password" value="" name="password" id="rcmLoginLinkPassword">

    <div class="buttons">
        <button><div data-textEdit="loginButton">Login</div></button>
        <button style="display:none;" class="processingButton"><div data-textEdit="processingButton">
                <span>Please wait...</span>
            <img src="/modules/rcm/images/busy-spinner-16x16.gif" width="16" height="16"></div>
        </button>
    </div>
</div>