<?php

/**
 * RcmSocialButtons content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-social-buttons/shareThisLoader.js',
    'text/javascript'
);
?>

<a class="rcmShareThisKey"
   data-rcmShareThisKey="<?=  $this->ic['shareThisKey']?>"></a>

<div class="rcmSocialButtonsWrapper">
    <?php foreach ($this->ic['buttons'] as $button): ?>
        <span class='st_<?=  $button . $this->ic['style']?>'>
        </span>
    <?php endforeach ?>
</div>