<?php

/**
 * RcmSocialButtons content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 */
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-social-buttons/shareThisLoader.js',
    'text/javascript'
);
?>
<script type="application/javascript">
    var RcmSocialButtonsAvailableButtonsForEdit = <?=json_encode($availableButtons)?>;
</script>

<a class="rcmShareThisKey"
   data-rcmShareThisKey="<?= $this->instanceConfig['shareThisKey'] ?>"></a>

<div class="rcmSocialButtonsWrapper">
    <?php foreach ($this->instanceConfig['buttons'] as $button): ?>
        <span class='st_<?= $button . $this->instanceConfig['style'] ?>'>
        </span>
    <?php endforeach ?>
</div>