<?php

/**
 * RcmSocialButtons content template
 *
 * Used for rendering simple content
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-social-buttons/shareThisLoader.js',
    'text/javascript'
);
?>

<div class="rcmSocialButtonsWrapper">
    <?php foreach ($this->data->buttons as $button): ?>
        <span class='st_<?php echo $button . $this->data->style?>'>
        </span>
    <?php endforeach ?>
</div>
<a class="rcmShareThisKey"
   data-rcmShareThisKey="<?php echo $this->data->shareThisKey?>"></a>