<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmMultiPageForm\Module'                                     => __DIR__ . '/Module.php',
  'RcmResetPassword\Controller\AbstractMultiPageFromController' => __DIR__ . '/src/RcmMultiPageForm/Controller/AbstractMultiPageFromController.php',
  'RcmMuliPageForm\Form\AbstractForm'                           => __DIR__ . '/src/RcmMultiPageForm/Form/AbstractForm.php',
  'RcmMuliPageForm\Model\StepModel'                             => __DIR__ . '/src/RcmMultiPageForm/Model/StepModel.php',
);
