<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmRotatingImage\Controller\PluginController'     => __DIR__ . '/src/RcmRotatingImage/Controller/PluginController.php',
    'RcmRotatingImage\Module'                          => __DIR__ . '/Module.php',
    'RcmRotatingImage\Controller\PluginControllerTest' => __DIR__ . '/tests/Controller/PluginControllerTst.php',
    'RcmRotatingImage\Module\ModuleTest'               => __DIR__ . '/tests/Module/ModuleTest.php',
    'RcmRotatingImageContentTest'                      => __DIR__ . '/tests/Entity/RandomImageTst.php',
);