<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmRotatingImage\Controller\PluginController'               => __DIR__ . '/src/RcmRotatingImage/Controller/PluginController.php',
    'RcmRotatingImage\Module'                                    => __DIR__ . '/Module.php',
    'RcmRotatingImage\Tests\Src\Controller\PluginControllerTest' => __DIR__ . '/tests/src/RcmRotatingImage/Controller/PluginControllerTest.php',
    'RcmRotatingImage\Tests\Bootstrap'                           => __DIR__ . '/tests/Bootstrap.php',
);