<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmJavaSciptLib\Module'                        => __DIR__ . '/Module.php',
  'RcmJavaSciptLib\Controller\TestController'     => __DIR__ . '/src/RcmJavaSciptLib/Controller/TestController.php',
  'RcmJavaSciptLib\View\Helper\IncludeHtmlEditor' => __DIR__ . '/src/RcmJavaSciptLib/View/Helper/IncludeHtmlEditor.php',
);
