<?php

/**
 * RcmEventListDisplay content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 */

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-social-buttons/shareThisLoader.js',
    'text/javascript'
);

$eventUrl = '//' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']
    . '#event';

?>

<div class="dataContainer"
     style="display:none;"
     data-eventCategoryId="<?=  $data->category?>"
        >
    <a class="rcmShareThisKey"
       data-rcmShareThisKey="<?=  $this->ic['shareThisKey']?>"></a>
</div>

<?php if(count($this->events)):?>

    <?php foreach($this->events as $event):?>
        <div class="event"
             data-eventCategoryId="<?=  $event->getCategory()->getCategoryId()?>"
             data-eventId="<?=  $event->getEventId()?>"
            >
            <a name="event<?=  $event->getEventId()?>"></a>
            <h3><?=  $event->getTitle()?></h3>
            <div class="days">
                <?=  $event->getDaysText()?>
            </div>
            <?=  $event->getText()?>
            <div class="eventFoot">
                <span class="st_sharethis"
                     st_title="<?=  $event->getText()?>"
                     st_url="<?=  $eventUrl . $event->getEventId()?>"
                     displayText='Share'>
                </span>
                -&nbsp;&nbsp;
                <a href="https://maps.google.com/maps?saddr=&daddr=<?php
                    echo urlencode($event->getMapAddress())
                   ?>"
                   target="_blank"
                    >
                    <?=  $this->ic['translate']['directions']?>
                </a>
            </div>
        </div>
        <br>
    <?php endforeach?>

<?php else:?>
    <div class="noEvent">
        <?=  $this->ic['translate']['noEvents']?>
    </div>
<?php endif?>