<?php
/**
 * Visitor-facing plugin template
 *
 * Visitor-facing plugin template
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   RcmPlugins\Navigation
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-login/style.css'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-login/rcm-login.js',
    'text/javascript'
);
echo $this->rcmJsLoginManager();
?>
<script type="text/javascript">
    $(function () {
        new RcmLoginOpenSourceVersionTempRename(
        <?php echo $this->instanceId?>,
        <?php echo json_encode($this->ic['errors'])?>
        );
    });
</script>



<h1 data-textEdit="loginHeader">
    <?php echo $this->ic['loginHeader']; ?>
</h1>

<div class="error"></div>


<label data-textEdit="userNameCopy" for="rcmLoginUsername">
    <?php echo $this->ic['userNameCopy']; ?>
</label>
<br>
<form>
    <input autofocus type="text" name="userName"
           class="username"
           id="rcmLoginUsername">
    <br>
    <label data-textEdit="loginPasswordCopy"
           for="rcmLoginPassword">
        <?php echo $this->ic['loginPasswordCopy']; ?>
    </label>
    <br>
    <input type="password" name="loginPass" class="password"
           id="rcmLoginPassword">

    <br>
    <br>

    <button class="login" data-textEdit="loginSubmitCopy">
        <?php echo $this->ic['loginSubmitCopy']; ?>
    </button>
</form>
<br>
<br>

<div data-richedit="bottomLoginText">
    <?php echo $this->ic['bottomLoginText']; ?>
</div>

