<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmSocialButtons\Module' => __DIR__ . '/Module.php',
    'RcmSocialButtons\Controller\PluginController' =>
        __DIR__ . '/src/RcmSocialButtons/Controller/PluginController.php',
    'RcmSocialButtons\Controller\PluginControllerTest' =>
        __DIR__ . '/tests/Controller/PluginControllerTest.php',
    'RcmSocialButtons\Module\ModuleTest' =>
        __DIR__ . '/tests/Module/ModuleTest.php',
];
