<?php
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-issuu/fit-container.js'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-issuu/rcm-issuu.js'
);

$docName = '';
$userName = '';
$embed = '<div class="issuuError">Please edit this plugin and select a document to show</div>';

if (!empty($this->instanceConfig['userName'])) {
    $userName = $this->instanceConfig['userName'];
}

if (!empty($this->instanceConfig['docName'])) {
    $docName = $this->instanceConfig['docName'];
}

if (!empty($this->instanceConfig['embed'])) {
    $embed = $this->instanceConfig['embed'];
}

?>

<div class="issuuEmbedContainer"
     data-userName="<?= $userName; ?>"
     data-docName="<?= $docName; ?>"
     data-embed="<?= htmlentities($embed, ENT_QUOTES) ?>"
>
    <?= $embed ?>
</div>