<?php
?>
<html lang="en" ng-app="RcmAdmin"><!-- <TEST_RCM_ADMIN> -->
<head>
    <style type="text/css">@charset "UTF-8";
        [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide {
            display: none !important;
        }

        ng\:form {
            display: block;
        }

        .ng-animate-block-transitions {
            transition: 0s all !important;
            -webkit-transition: 0s all !important;
        }

        .ng-hide-add-active, .ng-hide-remove {
            display: block !important;
        }
    </style>
    <meta charset="utf-8">
    <title>Reliv Login - Reliv International
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript"
            src="/modules/rcm-jquery/jquery-ui-1.10.4.custom/js/jquery-1.10.2.js">
    </script>
    <script type="text/javascript"
            src="/modules/rcm-jquery/jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.min.js">
    </script>
    <script type="text/javascript"
            src="/modules/rcm-twitter-bootstrap/bootstrap/js/bootstrap.js">
    </script>
    <script type="text/javascript" src="/modules/rcm-admin/js/rcm-admin.js">
    </script>
    <script type="text/javascript"
            src="/modules/rcm-plugin-helpers/form-double-submit-protect/form-double-submit-protect.js">
    </script>
    <script type="text/javascript"
            src="/modules/rcm-angular-js/angular/angular.min.js">
    </script>
    <script type="text/javascript">
        //<!--
        var RcmOrderMgrInitData = {"bagApi": "\/rcm-shopping-cart\/bag", "bagData": {"items": [], "subtotal": 0, "bvSubtotal": 0, "pvSubtotal": 0, "itemCount": 0, "formattedSubtotal": "$0.00", "bv": 0, "pv": 0, "formattedPv": "0.00", "formattedBv": "0.00"}}
        //-->
    </script>
    <script type="text/javascript"
            src="/modules/rcm-shopping-cart/js/models/RcmOrderMgr.js">
    </script>
    <script type="text/javascript"
            src="/modules/rcm-global-bag-display/RcmGlobalBagDisplayCtrl.js">
    </script>
    <script type="text/javascript"
            src="/modules/rcm-google-search-box/rcm-google-search-box.js">
    </script>
    <script type="text/javascript" src="/modules/rcm-rss-feed/RssReader.js">
    </script>

    <!-- <TEST_RCM_ADMIN> -->
    <script type="text/javascript" src="/modules/rcm-tinymce-js/tinymce/tinymce.js">
    </script>
    <script type="text/javascript" src="/modules/rcm-lib/rcm-html-editor/rcm-html-editor.js">
    </script>
    <script type="text/javascript" src="/modules/rcm-lib/rcm-core/rcm-admin.js">
    </script>
    <link href="/modules/rcm-lib/rcm-html-editor/rcm-html-editor.css" media="screen,print"
          rel="stylesheet" type="text/css">
    <!-- </TEST_RCM_ADMIN> -->

    <link href="/modules/rcm-admin/css/rcm-admin-navigation.css" media="screen,print"
          rel="stylesheet" type="text/css">
    <link href="/modules/rcm-twitter-bootstrap/css/bootstrap/bootstrap.min.css" media="screen"
          rel="stylesheet" type="text/css">
    <link href="/modules/rcm-jquery/jquery-ui-1.10.4.custom/css/smoothness/jquery-ui-1.10.4.custom.min.css"
          media="screen" rel="stylesheet" type="text/css">
    <link href="/images/favicon.ico" rel="shortcut icon"
          type="image/vnd.microsoft.icon">
    <link href="/modules/rcm-admin/css/rcm-admin-panel.css" media="screen,print"
          rel="stylesheet" type="text/css">
    <link href="/modules/rcm-navigation/style.css" media="screen" rel="stylesheet"
          type="text/css">
    <link href="/modules/rcm-login-link/style.css" media="screen" rel="stylesheet"
          type="text/css">
    <link href="/modules/rcm-global-bag-display/style.css" media="screen"
          rel="stylesheet" type="text/css">
    <link href="/modules/rcm-rss-feed/style.css" media="screen" rel="stylesheet"
          type="text/css">
    <link href="/modules/rcm-email-subscribe/style.css" media="screen"
          rel="stylesheet" type="text/css">
    <link href="/modules/reliv-guest-site/css/guestLayout.css" media="screen,print"
          rel="stylesheet" type="text/css">
    <link href="/modules/reliv-guest-site/css/guestSiteFonts.css" media="screen"
          rel="stylesheet" type="text/css">
    <meta name="viewport" content="width=1024, initial-scale=1">
</head>
<body style="">
<!-- STATIC TEST: -->
<div class="rcmAdminPanelWrapper">
    <div class="rcmAdminNavigation">
        <ul class="navigation">
            <li>
                <a href="#">Page
                </a>
                <ul>
                    <li>
                        <a href="#">New
                        </a>
                        <ul>
                            <li class="RcmAdminMenu RcmFormDialog">
                                <a title="New Page" href="/rcm-admin/page/new">Page
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Edit
                        </a>
                        <ul>
                            <li class="RcmAdminMenu RcmBlankDialog">
                                <a href="/modules/rcm-admin/page-properties.html">Page Properties
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">Site
                </a>
                <ul>
                    <li class="RcmAdminMenu RcmBlankDialog">
                        <a href="/modules/rcm-i18n/message-editor.html">Translations
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">Users
                </a>
                <ul>
                    <li>
                        <a href="/admin/rcmuser-acl">Roles and Access
                        </a>
                    </li>
                    <li>
                        <a href="/admin/rcmuser-users">User Management
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- <TEST_RCM_ADMIN> -->
    <div style="float: left; min-height:70px; width: 100%; ">
        <div html-editor-toolbar="">
        </div>
    </div>
    <!-- </TEST_RCM_ADMIN> -->

</div>
<div id="RcmStandardDialogTemplate" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">×
                </button>
                <h1 class="modal-title" id="myModalLabel">Modal title
                </h1>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">Close
                </button>
                <button type="button" class="btn btn-primary saveBtn">Save
                </button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="AdminDialogWindow" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
</div>
<!--Main Theme Body-->
<div id="sitewrapper">
    <!-- <TEST_RCM_ADMIN> -->
    <div
        XXdata-rcm-html-edit="something"
        data-trcmpluginname="TEST"
        ng-model="myModel.a"
        style="position: relative"
        >
        rcmHtmlEdit
    </div>
    <!-- </TEST_RCM_ADMIN> -->
    <a href="/">
        <div id="relivlogo">
        </div>
    </a>

    <div id="relivTopNavigation">
        <div class="rcmContainer" data-containerid="guestTopNavigation"
             data-containerrevision="14112" id="guestTopNavigation">
            <div class="rcmPlugin RcmNavigation CountrySelector "
                 data-rcmpluginname="RcmNavigation"
                 data-rcmplugininstanceid="23165"
                 data-rcmsitewideplugin="1"
                 data-rcmpluginresized="N"
                 data-rcmplugindisplayname="Country Selector"
                 style=" float: left; float: left; ">
                <div class="rcmPluginContainer">
                    <ul>
                        <li class="US country">
                            <a href="#">countries
                            </a>

                            <div class="popup columnCount_2">
                                <ul class="column column_1 ui-sortable">
                                    <li class="US country">
                                        <a href="//local.reliv.com">United States
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.reliv.com">English
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.spa.reliv.com">Español
                                        </a>
                                    </li>
                                    <li class="CA country">
                                        <a href="//local.relivinc.ca">Canada
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.relivinc.ca">English
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.fre.relivinc.ca">Français
                                        </a>
                                    </li>
                                    <li class="MX country">
                                        <a href="//local.reliv.mx">Mexico
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.reliv.mx">Español
                                        </a>
                                    </li>
                                    <li class="UK country">
                                        <a href="//local.reliv.co.uk">European Union
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.reliv.co.uk">English
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.reliv.de">Deutsch
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.reliv.fr">Français
                                        </a>
                                    </li>
                                </ul>
                                <ul class="column column_2 ui-sortable">
                                    <li class="AU country">
                                        <a href="//local.relivasiapacific.com.au">Australia
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.relivasiapacific.com.au">English
                                        </a>
                                    </li>
                                    <li class="NZ country">
                                        <a href="//local.relivasiapacific.co.nz">New Zealand
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.relivasiapacific.co.nz">English
                                        </a>
                                    </li>
                                    <li class="PH country">
                                        <a href="//local.relivasiapacific.com.ph">Philippines
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.relivasiapacific.com.ph">English
                                        </a>
                                    </li>
                                    <li class="MY country">
                                        <a href="//local.relivasiapacific.com.my">Malaysia
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.relivasiapacific.com.my">English
                                        </a>
                                    </li>
                                    <li class="SG country">
                                        <a href="//local.relivasiapacific.com.sg">Singapore
                                        </a>
                                    </li>
                                    <li>
                                        <a href="//local.relivasiapacific.com.sg">English
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="rcmPlugin RcmNavigation GuestSiteTopNav "
                 data-rcmpluginname="RcmNavigation"
                 data-rcmplugininstanceid="23166"
                 data-rcmsitewideplugin="1"
                 data-rcmpluginresized="N"
                 data-rcmplugindisplayname="Guest Site Top Nav"
                 style=" float: left; float: left; ">
                <div class="rcmPluginContainer">
                    <ul>
                        <li>
                            <a href="/">home
                            </a>
                        </li>
                        <li>
                            <a href="/distributor-application">become a distributor
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="rcmPlugin RcmLoginLink GuestSiteTopLogin "
                 data-rcmpluginname="RcmLoginLink" data-rcmplugininstanceid="23167"
                 data-rcmsitewideplugin="1" data-rcmpluginresized="N"
                 data-rcmplugindisplayname="Guest Site Top Login"
                 style=" float: left; float: left; ">
                <div class="rcmPluginContainer">
                    <div class="linkWrap  loggedIn">
                        <a href="/profile" class="profile">
                            <span data-textedit="profile"> my account
                            </span>
                        </a>
                        <a href="/autoship-orders/list" class="autoship">
                            <span data-textedit="autoship"> my autoship
                            </span>
                        </a>
                        <a href="" class="portal">
                            <span data-textedit="portal"> my portal
                            </span>
                        </a>
                        <a href="/login" class="login">
                            <span data-textedit="login"> login
                            </span>
                        </a>
                        <a href="/login?logout=1" class="logout">
                            <span data-textedit="logout"> logout
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="rcmPlugin RcmGlobalBagDisplay SiteCheckoutButton "
                 data-rcmpluginname="RcmGlobalBagDisplay"
                 data-rcmplugininstanceid="23168" data-rcmsitewideplugin="1"
                 data-rcmpluginresized="N"
                 data-rcmplugindisplayname="Site Checkout Button"
                 style=" float: left; float: none; ">
                <div class="rcmPluginContainer">
                    <div XXng-controller="RcmGlobalBagDisplayCtrl" class="ng-scope">
                        <div>
                            <a href="/checkout/cart">
                                <img src="//static.reliv.com/art/WebStuff/Cart/Cart-web.png"
                                     class="cartImg">
                                <span class="itemCountVal ng-binding">0
                                </span>
                                <div class="cartDiv" data-textedit="cart">
                                    <p>cart
                                    </p>
                                </div>
                            </a>
                        </div>
                        <div class="popCart ng-hide" ng-show="bag.items">
                            <!-- ngRepeat: item in bag.items -->
                            <a class="button" data-textedit="cartButton"
                               href="/checkout/cart"> view cart
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="relivNavStretchedBar">
        <div id="relivNavBar">
            <div class="rcmContainer" data-containerid="guestMainNavigation"
                 data-containerrevision="14113" id="guestMainNavigation">
                <div class="rcmPlugin RcmNavigation SiteNavigation "
                     data-rcmpluginname="RcmNavigation"
                     data-rcmplugininstanceid="23169"
                     data-rcmsitewideplugin="1"
                     data-rcmpluginresized="N"
                     data-rcmplugindisplayname="Site Navigation"
                     style=" float: left; float: left; ">
                    <div class="rcmPluginContainer">
                        <ul>
                            <li class="">
                                <a href="/what-is-reliv">About Us
                                </a>

                                <div class="popup columnCount_1">
                                    <ul class="column column_1 ui-sortable">
                                        <li class="heading">
                                            <a href="/#">Who We Are
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/reliv-story">Reliv Story
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/executives-of-reliv">Executives
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/reliv-international-world-wide-offices">Worldwide Offices
                                            </a>
                                        </li>
                                        <li class="heading">
                                            <a href="#">Corporate Social Responsibility
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/reliv-core-values">Core Values
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/reliv-values-in-action">Values in Action
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/reliv-kalogris-foundation">Reliv Kalogris Foundation
                                            </a>
                                        </li>
                                        <li class="heading">
                                            <a href="#">The Science of Reliv
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/advanced-nutrition">Advanced Nutrition
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/reliv-difference">Reliv Difference
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/soy-supplements">Soy Supplements
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/reliv-lunarich-soy-powder">LunaRich
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/lunasin-and-epigenetics">Lunasin and Epigenetics
                                            </a>
                                        </li>
                                        <li class="heading">
                                            <a href="/reliv-newsroom">Newsroom
                                            </a>
                                        </li>
                                        <li class="bold">
                                            <a href="/frequently-asked-questions">FAQ
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li class="">
                                <a href="/reliv-products">Products
                                </a>

                                <div class="popup columnCount_2">
                                    <ul class="column column_1 ui-sortable">
                                        <li style="" class="heading">
                                            <a href="/all-shopping">All Shopping
                                            </a>
                                        </li>
                                        <li style="" class="bold">
                                            <a href="/quick-shop">Quick Shop
                                            </a>
                                        </li>
                                        <li class="heading">
                                            <a href="/lunarich-products">LunaRich Products
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/p/lunarich-x">LunaRich X
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/p/reliv-now">Reliv Now
                                            </a>
                                        </li>
                                        <li class="" style="">
                                            <a href="/p/glucaffect">GlucAffect
                                            </a>
                                        </li>
                                        <li style="" class="">
                                            <a href="/p/provantage">ProVantage
                                            </a>
                                        </li>
                                        <li class="" style="">
                                            <a href="/p/reliv-now-for-kids">Reliv Now for Kids
                                            </a>
                                        </li>
                                        <li style="" class="">
                                            <a href="/p/slimplicity-vanilla">Slimplicity Vanilla
                                            </a>
                                        </li>
                                        <li class="" style="">
                                            <a href="/p/soysentials">SoySentials
                                            </a>
                                        </li>
                                        <li class="heading">
                                            <a href="/nutritional-products">More Nutritional Products
                                            </a>
                                        </li>
                                        <li class="" style="">
                                            <a href="/p/24k">24K
                                            </a>
                                        </li>
                                        <li style="" class="">
                                            <a href="/p/arthaffect">Arthaffect
                                            </a>
                                        </li>
                                        <li style="" class="">
                                            <a href="/p/cardiosentials">CardioSentials
                                            </a>
                                        </li>
                                        <li style="" class="">
                                            <a href="/p/cellebrate">Cellebrate
                                            </a>
                                        </li>
                                        <li style="" class="">
                                            <a href="/p/fibrestore">FibRestore
                                            </a>
                                        </li>
                                        <li style="" class="">
                                            <a href="/p/innergize">Innergize!
                                            </a>
                                        </li>
                                        <li style="" class="">
                                            <a href="/p/reliv-classic">Reliv Classic
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/p/reversage">ReversAge
                                            </a>
                                        </li>
                                    </ul>
                                    <ul class="column column_2 ui-sortable">
                                        <li class="heading">
                                            <a href="/skincare">Skincare
                                            </a>
                                        </li>
                                        <li class="" style="">
                                            <a href="/p/womens-r-collection">r collection
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/p/r-day">r day
                                            </a>
                                        </li>
                                        <li class="" style="">
                                            <a href="/p/r-night">r night
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/p/r-eye-complex">r eye complex
                                            </a>
                                        </li>
                                        <li class="" style="">
                                            <a href="/p/r-cleanser">r cleanser
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/p/r-body-revitalizing-moisture">r body
                                            </a>
                                        </li>
                                        <li style="" class="heading">
                                            <a href="/nutritional-products">Other Products
                                            </a>
                                        </li>
                                        <li style="" class="">
                                            <a href="/p/all-natural-sweetener">All-Natural Sweetener
                                            </a>
                                        </li>
                                        <li class="" style="">
                                            <a href="/p/reliv-delight">Reliv Delight
                                            </a>
                                        </li>
                                        <li style="" class="heading">
                                            <a href="/business-tools">Business Tools
                                            </a>
                                        </li>
                                        <li style="" class="bold">
                                            <a href="/reliv-gear">Reliv Gear
                                            </a>
                                        </li>
                                        <li style="" class="bold">
                                            <a href="/p/kalogris-donation">Kalogris Donation
                                            </a>
                                        </li>
                                        <li style="" class="heading">
                                            <a href="/reliv-product-reviews">Product Reviews
                                            </a>
                                        </li>
                                        <li style="" class="bold">
                                            <a href="/reliv-product-frequently-asked-questions">Product FAQ
                                            </a>
                                        </li>
                                        <li style="" class="bold">
                                            <a href="/login">Get Reliv
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li class="">
                                <a href="/reliv-opportunity">Opportunity
                                </a>

                                <div class="popup columnCount_1">
                                    <ul class="column column_1 ui-sortable">
                                        <li style="" class="heading">
                                            <a href="/get-started-with-reliv">Get Started
                                            </a>
                                        </li>
                                        <li class="bold">
                                            <a href="/how-reliv-works">How Reliv Works
                                            </a>
                                        </li>
                                        <li class="bold">
                                            <a href="/reliv-conferences">IMPACT Events
                                            </a>
                                        </li>
                                        <li class="bold">
                                            <a href="http://www.relivinternationalconference.com/US/EN/home.html">International Conference
                                            </a>
                                        </li>
                                        <li style="" class="bold">
                                            <a href="/travel-with-reliv">Travel with Reliv
                                            </a>
                                        </li>
                                        <li class="heading">
                                            <a href="#">Success Stories
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/opportunity-stories">Opportunity Stories
                                            </a>
                                        </li>
                                        <li class="">
                                            <a href="/meet-our-reliv-ambassadors">Top Earners
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li class="">
                                <a href="http://blog.reliv.com">Reliv Blog
                                </a>

                                <div class="popup columnCount_1">
                                    <ul class="column column_1 ui-sortable">
                                        <li class="heading">
                                            <a href="http://blog.reliv.com/category/healthy-living-tips/">Healthy Living Tips
                                            </a>
                                        </li>
                                        <li class="bold">
                                            <a href="http://blog.reliv.com/category/science-health/">Science &amp; Health Today
                                            </a>
                                        </li>
                                        <li class="bold">
                                            <a href="http://blog.reliv.com/category/nutrition/my-story/">Product Stories
                                            </a>
                                        </li>
                                        <li class="bold">
                                            <a href="http://blog.reliv.com/category/reliv-home-business/success-stories/">Business Stories
                                            </a>
                                        </li>
                                        <li class="bold">
                                            <a href="http://blog.reliv.com/category/recipes/">Recipes
                                            </a>
                                        </li>
                                        <li class="bold">
                                            <a href="/lifestyle">Lifestyle Magazine
                                            </a>
                                        </li>
                                        <li class="bold">
                                            <a href="/this-month-at-reliv">This Month @Reliv
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="relivTopSpacer">
    </div>
    <div id="relivMainBody">
        <div id="relivLeftColumn">
        </div>
        <div id="relivRightColumn">
            <div class="rcmContainer" data-containerid="guestRightColumn"
                 data-containerrevision="14114" id="guestRightColumn">
                <div class="rcmPlugin RcmGoogleSearchBox SiteSearchBox "
                     data-rcmpluginname="RcmGoogleSearchBox"
                     data-rcmplugininstanceid="8727" data-rcmsitewideplugin="1"
                     data-rcmpluginresized="N"
                     data-rcmplugindisplayname="Site Search Box"
                     style=" float: left; float: left; ">
                    <div class="rcmPluginContainer">
                        <script type="text/javascript"> $(function () {
                                new RcmGoogleSearchBox(8727);
                            });
                        </script>
                        <form action="/search">
                            <input type="hidden" name="cx"
                                   value="000756681373664777195:za-qx2oocbk">
                            <input type="hidden" name="ie" value="UTF-8">
                            <input type="hidden" name="q">
                            <input value="" type="text" name="qq" size="40">
                            <button class="plain search">Search
                            </button>
                        </form>
                    </div>
                </div>
                <div class="rcmPlugin RcmHtmlArea ShareIcons "
                     data-rcmpluginname="RcmHtmlArea"
                     data-rcmplugininstanceid="14778" data-rcmsitewideplugin="1"
                     data-rcmpluginresized="N"
                     data-rcmplugindisplayname="Share Icons"
                     style=" float: left; float: left; ">
                    <div class="rcmPluginContainer">
                        <div data-richedit="html" style="width:100%">
                            <p>
                                <a href="http://facebook.com/reliv">
                                    <img src="//static.reliv.com/migrate/themes/reliv-guest-site/social-buttons/facebook.png"
                                         alt="facebook.png">
                                </a>
                                <a href="http://twitter.com/reliv">
                                    <img src="//static.reliv.com/migrate/themes/reliv-guest-site/social-buttons/twitter.png"
                                         alt="twitter.png">
                                </a>
                                <a href="https://plus.google.com/112177336108301286674/posts">
                                    <img src="//static.reliv.com/migrate/themes/reliv-guest-site/social-buttons/google.png"
                                         alt="google.png">
                                </a>
                                <a href="http://youtube.com/relivinternational">
                                    <img src="//static.reliv.com/migrate/themes/reliv-guest-site/social-buttons/youtube.png"
                                         alt="youtube.png">
                                </a>
                            </p>

                            <p>
                                <strong>800.735.4887
                                </strong>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="rcmPlugin RcmRssFeed RelivBlogFeed "
                     data-rcmpluginname="RcmRssFeed" data-rcmplugininstanceid="9645"
                     data-rcmsitewideplugin="1" data-rcmpluginresized="N"
                     data-rcmplugindisplayname="Reliv Blog Feed"
                     style=" float: left; float: left; ">
                    <div class="rcmPluginContainer">
                        <script type="text/javascript"> $(function () {
                                new RssReader('/rcm-rss-proxy', 9645,
                                              $(".rss-feed-9645"), null);
                            });
                        </script>
                        <div class="rcmRssFeedReaderMainContainer"
                             data-rcmrssfeedurl="//blog.reliv.com/feed/"
                             data-rcmrssfeedlimit="4"
                             data-rcmrssfeedproxy="/rcm-rss-proxy">
                            <h2 data-textedit="headline">Reliv Blog
                            </h2>
                            <span class="rss-feed-9645">
                                <p>There was a problem retrieving the RSS feed
                                </p>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="rcmPlugin RcmEmailSubscribe EmailSignUp "
                     data-rcmpluginname="RcmEmailSubscribe"
                     data-rcmplugininstanceid="23170" data-rcmsitewideplugin="1"
                     data-rcmpluginresized="N"
                     data-rcmplugindisplayname="Email Sign Up"
                     style=" float: left; float: left; ">
                    <div class="rcmPluginContainer">
                        <div data-richedit="topText">
                            <div aria-describedby="cke_1102"
                                 aria-label="Rich Text Editor, 11624_rcm_richEdit_RcmEmailSubscribe_11624_topText"
                                 contenteditable="true"
                                 id="11624_rcm_richEdit_RcmEmailSubscribe_11624_topText"
                                 role="textbox" spellcheck="false"
                                 style="position: relative;" tabindex="0"
                                 title="Rich Text Editor, 11624_rcm_richEdit_RcmEmailSubscribe_11624_topText">
                                <h2>Learn to live better
                                </h2>

                                <div>Sign up to receive Reliv's
                                    <strong>
                                        <i>Healthy Living Tips
                                        </i>
                                    </strong>.
                                </div>
                            </div>
                        </div>
                        <form action="" method="post">
                            <input name="rcmPluginName" type="hidden"
                                   value="RcmEmailSubscribe">

                            <div class="error">
                            </div>
                            <label for="email"
                                   data-textedit="emailLabel">Email Address:
                            </label>
                            <input name="email" type="text" value="">

                            <div class="rcmEmailSubscribeSubmit">
                                <button data-textedit="submit"> Submit
                                </button>
                                <span class="arrowLogo">&nbsp;
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div id="relivCenter">
            <div class="rcmContainer"
                 data-containerid="4"
                 data-containerrevision="13568"
                 data-ispagecontainer="Y"
                 id="login"
                >
                <!-- <TEST_RCM_ADMIN> -->
                <!-- <INLINE> -
                <div class="example">
                    <p><b>EXAMPLE Attribute options div:</b></p>

                    <div id="htmlEditorToolbar-myEditor1">

                    </div>
                    <div
                        data-rcm-html-edit="somethingText"
                        html-editor-attached-toolbar
                        id="myEditor1"
                        >
                        OPTIONS ATTR
                    </div>
                </div>
                <!-- </INLINE> -->
                <div class="rcmPlugin RcmLogin LoginArea "
                     data-rcmpluginname="RcmLogin"
                     data-rcmplugininstanceid="22573"
                     data-rcmsitewideplugin=""
                     data-rcmpluginresized="N"
                     data-rcmplugindisplayname="Login Area"
                     ng-model="myModel.b"
                     style=" float: left; float: left; ">
                    <div class="rcmPluginContainer">
                        RcmLogin
                        <h1 data-textedit="loginHeader">
                            <div>
                                <span style="font-size:20px;line-height:22px;">Login
                                </span>
                                <br>
                            </div>
                        </h1>
                        <div class="error">
                        </div>
                        <form class="loginForm rcmDoubleSubmitProtect" method="post">
                            <label data-textedit="userNameCopy"
                                   for="rcmLoginUsername"> RCN or Username:
                            </label>
                            <br>
                            <input type="hidden" name="rcmPluginName"
                                   value="RcmLogin">
                            <input autofocus="" type="text" name="username" value="">
                            <br>
                            <label data-textedit="loginPasswordCopy"
                                   for="rcmLoginPassword"> Password:
                            </label>
                            <br>
                            <input type="password" name="password">
                            <br>
                            <br>
                            <button data-textedit="loginSubmitCopy"
                                    type="submit"> Login
                            </button>
                        </form>
                        <br>
                        <br>

                        <div data-richedit="bottomLoginText">
                            <p>
                                <strong>Don’t have an account yet?
                                </strong>
                                <br>
                                <a href="/customer-application">Request a customer account.
                                </a>
                                <br>
                                <a href="/distributor-application">Request a distributor account.
                                </a>
                            </p>

                            <p>&nbsp;
                            </p>

                            <p>
                                <a href="http://local.reliv.com/forgot-password">Forgot password?
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
                <!-- </TEST_RCM_ADMIN> -->
            </div>
        </div>
        <div style="clear: both;">
        </div>
    </div>
    <div id="footerpush">
    </div>
</div>
<div id="relivGuestFooterContainer">
    <div id="relivGuestFooter">
        <div class="rcmContainer" data-containerid="guestFooter"
             data-containerrevision="14115" id="guestFooter">
            <div class="rcmPlugin RcmHtmlArea FarLeftFooter "
                 data-rcmpluginname="RcmHtmlArea" data-rcmplugininstanceid="2642"
                 data-rcmsitewideplugin="1" data-rcmpluginresized="Y"
                 data-rcmplugindisplayname="FarLeftFooter"
                 style=" height: 85px; width: 130px; float: left; float: left; ">
                <div class="rcmPluginContainer">
                    <div data-richedit="html" style="width:100%">
                        <p>
                            <img src="//static.reliv.com/migrate/themes/reliv-guest-site/header-and-footer/thirty-day.png"
                                 alt="thirty-day.png">
                        </p>
                    </div>
                </div>
            </div>
            <div class="rcmPlugin RcmHtmlArea LeftFooter "
                 data-rcmpluginname="RcmHtmlArea" data-rcmplugininstanceid="6420"
                 data-rcmsitewideplugin="1" data-rcmpluginresized="Y"
                 data-rcmplugindisplayname="LeftFooter"
                 style=" height: 100px; width: 340px; float: left; float: left; ">
                <div class="rcmPluginContainer">
                    <div data-richedit="html" style="width:100%">
                        <p>
                            <span style="font-family:Verdana, Arial, Helvetica, sans-serif;font-size:10px;line-height:13px;">Copyright 2013&nbsp;International. All rights reserved.
                                <br> 136 Chesterfield Ind. Blvd., Chesterfield, MO 63005
                                <br> Toll free: 800.735.4887
                                <br> Phone 636.537.9715 | Fax 636.537.9753
                                <br>
                                <a href="/reliv-international-world-wide-offices">Contact Us
                                </a>&nbsp;|&nbsp;
                                <a href="//static.reliv.com/migrate/docs/US/EN/privacy_policy.pdf">Privacy Policy
                                </a>&nbsp;|&nbsp;
                                <a href="/investor-relations">Investor Relations
                                </a>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            <div class="rcmPlugin RcmHtmlArea MiddleFooter "
                 data-rcmpluginname="RcmHtmlArea" data-rcmplugininstanceid="6400"
                 data-rcmsitewideplugin="1" data-rcmpluginresized="Y"
                 data-rcmplugindisplayname="MiddleFooter"
                 style=" height: 81px; width: 190px; float: left; float: left; ">
                <div class="rcmPluginContainer">
                    <div data-richedit="html" style="width:100%">
                        <p>
                            <a href="/p/reversage">Anti-aging supplement
                            </a>
                            <br>
                            <a href="/p/glucaffect">Blood sugar management
                            </a>
                            <br>
                            <a href="/p/fibrestore">Digestive health
                            </a>
                            <br>
                            <a href="/p/24k">Healthy energy shot
                            </a>
                            <br>
                            <a href="/p/cardiosentials">Heart health
                            </a>
                            <br>
                            <a href="/p/arthaffect">Joint health
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="rcmPlugin RcmHtmlArea RightFooter "
                 data-rcmpluginname="RcmHtmlArea" data-rcmplugininstanceid="6933"
                 data-rcmsitewideplugin="1" data-rcmpluginresized="Y"
                 data-rcmplugindisplayname="RightFooter"
                 style=" height: 81px; width: 170px; float: left; float: left; ">
                <div class="rcmPluginContainer">
                    <div data-richedit="html" style="width:100%">
                        <p>
                            <a href="/reliv-lunarich-soy-powder">LunaRich Soy Powder
                            </a>
                            <br>
                            <a href="http://blog.reliv.com/?s=pycnogenol">Pycnogenol
                            </a>
                            <br>
                            <a href="http://blog.reliv.com">Reliv Blog
                            </a>
                            <br>
                            <a href="/soy-supplements">Soy supplements
                            </a>
                            <br>
                            <a href="http://www.facebook.com/teamreliv">Team Reliv
                            </a>
                            <br>
                            <a href="/p/slimplicity">Weight loss shake
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="rcmPlugin RcmHtmlArea FarRightFooter "
                 data-rcmpluginname="RcmHtmlArea" data-rcmplugininstanceid="3507"
                 data-rcmsitewideplugin="1" data-rcmpluginresized="Y"
                 data-rcmplugindisplayname="FarRightFooter"
                 style=" height: 101px; width: 160px; float: left; float: left; ">
                <div class="rcmPluginContainer">
                    <div data-richedit="html" style="width:100%">
                        <table border="0" cellpadding="1" cellspacing="1"
                               style="width:100%;">
                            <tbody>
                            <tr>
                                <td>
                                    <a href="http://www.bbb.org/stlouis/business-reviews/multi-level-selling-companies/reliv-international-in-chesterfield-mo-110115183">
                                        <img src="//static.reliv.com/migrate/themes/reliv-guest-site/header-and-footer/bbb.png"
                                             alt="bbb.png">
                                    </a>
                                </td>
                                <td>
                                    <a href="http://www.dsa.org/ethics/">
                                        <img src="//static.reliv.com/migrate/themes/reliv-guest-site/header-and-footer/dsa.png"
                                             alt="dsa.png">
                                        <br> Code of Ethics
                                    </a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Required CMS Body Bottom-->
</body>
</html>