<?php

/**
 * RcmEventCalender content template
 *
 * Used for rendering simple content
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */
?>
<div>
<?php foreach($this->events as $event):?>
    <?php var_dump($event) ?>
<?php endforeach ?>
</div>