<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmLoginLink\Controller\PluginController' => __DIR__ . '/src/RcmLoginLink/Controller/PluginController.php',
    'RcmLoginLink\Module'                      => __DIR__ . '/Module.php',
);