<link rel="stylesheet" type="text/css"
      href="<?= $this->basePath(); ?>/modules/rcm-admin/css/rcm-admin-page-form.css"
/>

<script type="text/javascript"
        src="<?= $this->basePath(); ?>/modules/rcm-admin/js/rcm-admin-page-form.js"
>

</script>

<?php

$form = $this->form;
$form->prepare();

$pageUrl = $form->get('url');
$pageTitle = $form->get('title');
$pageTemplate = $form->get('page-template');
$pageLayouts = $form->get('page-layout');

// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('RcmAdmin\Page\New'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Get the form label plugin
$formLabel = $this->plugin('formLabel');
?>

<?= $this->form()->openTag($form); ?>

<?= $this->message; ?><br/>

<?= $this->formElementErrors($pageUrl); ?>
<?= $formLabel->openTag() . $pageUrl->getOption('label'); ?> &nbsp;
<?= $this->formInput($pageUrl); ?>
<?= $formLabel->closeTag(); ?>

<br />

<?= $this->formElementErrors($pageTitle); ?>
<?= $formLabel->openTag() . $pageTitle->getOption('label'); ?> &nbsp;
<?= $this->formInput($pageTitle); ?>
<?= $formLabel->closeTag(); ?>

<br />

<div id="pageTemplate">
    <?= $this->formElementErrors($pageTemplate); ?>
    <?= $formLabel->openTag() . $pageTemplate->getOption('label'); ?> &nbsp;
    <?= $this->formSelect($pageTemplate); ?>
    <?= $formLabel->closeTag(); ?>
</div>

<div id="pageLayout">
    <?= $this->formElementErrors($pageLayouts); ?>
    <?= $formLabel->openTag(); ?>
    <div class="PageLayoutLabelDiv">
        <?= $pageLayouts->getOption('label'); ?>
    </div>
    <?= $this->formPageLayout($pageLayouts); ?>
    <?= $formLabel->closeTag(); ?>
    <div style="clear: both;"></div>
</div>

<?= $this->form()->closeTag(); ?>
