<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmSimpleConfigStorage\Controller\SimpleConfigStorageController' => __DIR__ . '/src/RcmSimpleConfigStorage/Controller/SimpleConfigStorageController.php',
    'RcmSimpleConfigStorage\StorageEngine\DoctrineSerializedRepo'     => __DIR__ . '/src/RcmSimpleConfigStorage/StorageEngine/DoctrineSerializedRepo.php',
    'RcmSimpleConfigStorage\Exception\RuntimeException'               => __DIR__ . '/src/RcmSimpleConfigStorage/Exception/RuntimeException.php',
    'RcmSimpleConfigStorage\Exception\PluginDataNotFoundException'    => __DIR__ . '/src/RcmSimpleConfigStorage/Exception/PluginDataNotFoundException.php',
    'RcmSimpleConfigStorage\Entity\InstanceConfig'                    => __DIR__ . '/src/RcmSimpleConfigStorage/Entity/InstanceConfig.php',
    'RcmSimpleConfigStorage\Module'                                   => __DIR__ . '/Module.php',
    'RcmSimpleConfigStorage\Module\ModuleTest'                        => __DIR__ . '/tests/Module/ModuleTest.php',
);