<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmSimpleConfigStorage\Controller\BasePluginController'            => __DIR__ . '/src/RcmSimpleConfigStorage/Controller/BasePluginController.php',
    'RcmSimpleConfigStorage\StorageEngine\DoctrineSerializedRepo'       => __DIR__ . '/src/RcmSimpleConfigStorage/StorageEngine/DoctrineSerializedRepo.php',
    'RcmSimpleConfigStorage\Exception\RuntimeException'                 => __DIR__ . '/src/RcmSimpleConfigStorage/Exception/RuntimeException.php',
    'RcmSimpleConfigStorage\Exception\PluginDataNotFoundException'      => __DIR__ . '/src/RcmSimpleConfigStorage/Exception/PluginDataNotFoundException.php',
    'RcmSimpleConfigStorage\Entity\InstanceConfig'                      => __DIR__ . '/src/RcmSimpleConfigStorage/Entity/InstanceConfig.php',
    'Bootstrap'                                                         => __DIR__ . '/test/Bootstrap.php',
    'RcmSimpleConfigStorage\Module\Controller\BasePluginControllerTest' => __DIR__ . '/test/RcmSimpleConfigStorageTest/Controller/BasePluginControllerTest.php',
    'RcmSimpleConfigStorage\Module'                                     => __DIR__ . '/Module.php',
);