<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmBrightcovePlayer\Module'                      => __DIR__ . '/Module.php',
  'RcmBrightcovePlayer\Controller\PluginController' => __DIR__ . '/src/RcmBrightcovePlayer/Controller/PluginController.php',
);
