<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmBrightcovePlayer\Module' => __DIR__ . '/Module.php',
    'RcmBrightcovePlayer\Factory\RcmBrightcovePlayerControllerFactory' =>
        __DIR__
        . '/src/RcmBrightcovePlayer/Factory/RcmBrightcovePlayerControllerFactory.php',
];
