<div class="rcmPanelRightButtons" data-rcm-admin-menu-actions>
    <div ng-show="rcmAdminPage.editMode">
        <div class="btn-group">
            <button
                class="btn btn-primary btn-xs"
                rcm-admin-edit-button="save"
                type="button"
                >
                <span
                    class="glyphicon glyphicon glyphicon glyphicon-ok"
                    ></span>
                Save Draft
            </button>
            <button
                class="btn btn-xs"
                rcm-admin-edit-button="cancel"
                type="button"
                >
                <span
                    class="glyphicon glyphicon glyphicon-remove"
                    ></span>
                Cancel
            </button>
        </div>
    </div>

    <div ng-hide="rcmAdminPage.editMode">
        <div class="btn-group">
            <?php if ($layout->rcmDraft === true) : ?>

                <button
                    class="btn btn-primary btn-xs rcmMenuPost"
                    type="button"
                    publish-url="<?=
                    $this->url(
                        'RcmAdmin\Page\PublishPageRevision',
                        array(
                            'rcmPageRevision' => $layout->pageInfo['revision']['revisionId'],
                            'rcmPageType' => $layout->pageInfo['pageType'],
                            'rcmPageName' => $layout->pageInfo['name'],
                        )
                    ); ?>"
                    >
                    <span class="glyphicon glyphicon-check"></span>
                    Publish
                </button>

            <?php endif; ?>


            <button
                class="btn btn-warning btn-xs"
                rcm-admin-edit-button="page"
                type="button"
                >
                <span class="glyphicon glyphicon-edit"></span>
                Edit
            </button>
        </div>
    </div>
</div>

<div style="clear: both;"></div>