<?php
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-admin/css/rcm-admin-panel.css',
    'screen,print'
);
?>

<div class="rcmAdminPanelWrapper">
    <?= $this->render('rcm-admin/admin/partial/navigation/navigation.phtml'); ?>
    <?php
    // Requires Angular and rcmJavaScriptLib/public/html-editor/html-editor.js
    // and a parent angular controller
    ?>
    <div html-editor-toolbar></div>
</div>
