<?php
// css
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-admin/css/rcm-admin-panel.css',
    'screen,print'
);

$layout = $this->layout();

?>
<!-- <panel> -->
<div class="rcmAdminPanelWrapper" ng-cloak>
    <div class="rcmAdminPanelFixed">
        <div class="rcmAdminPanelInner">
            <div class="rcmAdminPanelNav">
                <?=
                $this->render(
                    'rcm-admin/admin/partial/navigation/navigation.phtml'
                ); ?>
                <div class="rcmPanelRightButtons" data-rcm-admin-menu-actions>
                    <div ng-show="rcmAdminPage.editMode">
                        <div class="btn-group">
                            <button
                                class="btn btn-primary btn-xs"
                                rcm-admin-edit-button="save"
                                type="button"
                                >
                                <span
                                    class="glyphicon glyphicon glyphicon glyphicon-ok"
                                    ></span>
                                Save Draft
                            </button>
                            <button
                                class="btn btn-xs"
                                rcm-admin-edit-button="cancel"
                                type="button"
                                >
                                <span
                                    class="glyphicon glyphicon glyphicon-remove"
                                    ></span>
                                Cancel
                            </button>
                        </div>
                    </div>

                    <div ng-hide="rcmAdminPage.editMode">
                        <div class="btn-group">
                        <?php if ($layout->rcmDraft === true) : ?>

                                <button
                                    class="btn btn-primary btn-xs"
                                    rcm-admin-edit-button="publish"
                                    type="button"
                                    publish-url="<?= $this->url(
                                        'RcmAdmin\Page\PublishPageRevision',
                                        array(
                                            'rcmPageRevision' => $layout->pageInfo['revision']['revisionId'],
                                            'rcmPageType' => $layout->pageInfo['pageType'],
                                            'rcmPageName' => $layout->pageInfo['name'],
                                        )
                                    ); ?>"
                                >
                                    <span class="glyphicon glyphicon-check"></span>
                                    Publish
                                </button>

                        <?php endif; ?>


                            <button
                                class="btn btn-warning btn-xs"
                                rcm-admin-edit-button="page"
                                type="button"
                                >
                                <span class="glyphicon glyphicon-edit"></span>
                                Edit
                            </button>
                        </div>
                    </div>
                </div>

                <div style="clear: both;"></div>
            </div>

            <div class="rcmPanelEditorToolbar">
                <?php
                // Requires Angular and rcmLib/public/html-editor/html-editor.js
                // and a parent angular controller
                ?>
                <div html-editor-toolbar html-editor-toolbar-toggle="false"
                     html-editor-toolbar-default-skin="lightgray"></div>
            </div>

            <div style="clear: both;"></div>
        </div>
        <div class="rcmAdminPanelShadow" style="display:block;">
            <span></span>
        </div>
    </div>
</div>
<?= $this->availablePluginsList() ?>
<!-- </panel> -->
