<?php
$this->rcmJsLibIncludeCoreJs();

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-tinymce-js/tinymce/tinymce.js'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-js-lib/rcm-html-editor/rcm-html-editor.js'
);
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-js-lib/rcm-core/rcm-admin.js'
);

// css
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-admin/css/rcm-admin-panel.css',
    'screen,print'
);

?>
<div class="rcmAdminPanelWrapper">
    <?= $this->render('rcm-admin/admin/partial/navigation/navigation.phtml'); ?>
    <div class="rcmPanelRightButtons">
        <!--    NOTE: BOOTSTRAP BUTTON GROUPS MIGHT LOOK NICE IF WE HAVE
        MORE THAN ONE LIKE FOR [PUBLISH] /[CANCEL] -->
        <button type="button" class="btn btn-primary btn-xs">
            <span class="glyphicon glyphicon-edit"></span>
            Edit
        </button>
    </div>
    <?php
    // Requires Angular and rcmJavaScriptLib/public/html-editor/html-editor.js
    // and a parent angular controller
    ?>
    <br/>

    <div html-editor-toolbar></div>
</div>
