<?php
$this->headScript()->appendFile(
    '/modules/rcm-plugin-helpers/form-double-submit-protect/form-double-submit-protect.js',
    'text/javascript'
);

$this->rcmJsLibIncludeCoreJs();
//needed for form-double-submit-protect.js
?>

<?=
$this->rcmTextEdit(
    'loginHeader',
    'Login',
    'h1'
)
?>

<div class="error">
    <?= isset($error) ? $this->escapeHtml($error) : '' ?>
</div>

<form class="loginForm rcmDoubleSubmitProtect" action="#" method="post">
    <?=
    $this->rcmTextEdit(
        'userNameCopy',
        'Username:',
        'label',
        array('for' => 'rcmLoginUsername')
    ) ?>
    <br>
    <input type="hidden" name="rcmPluginName" value="RcmLogin">
    <input autofocus type="text" name="username"
           value="<?= $this->escapeHtml($username) ?>">
    <br>
    <?=
    $this->rcmTextEdit(
        'loginPasswordCopy',
        'Password:',
        'label',
        array('for' => 'rcmLoginPassword')
    ) ?>
    <br>
    <input type="password" name="password">

    <br>
    <br>
    <button class="btn btn-primary">
        <?=
        $this->rcmTextEdit(
            'loginSubmitCopy',
            'login',
            'span',
            array('type' => 'submit')
        ) ?>
    </button>
</form>
<br>
<br>

<?=
$this->rcmRichEdit(
    'bottomLoginText',
    '<a href="/reset-password">Forgot your password?</a><br>'
) ?>

