<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmHtmlEditor\Module'                        => __DIR__ . '/Module.php',
    'RcmHtmlEditor\View\Helper\IncludeHtmlEditor' => __DIR__ . '/src/RcmHtmlEditor/View/Helper/IncludeHtmlEditor.php',
);
