<?php
$this->headLink()->prependStylesheet(
    $this->basePath() . '/modules/rcm-admin/css/rcm-admin-navigation.css',
    'screen,print'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-admin/js/rcm-admin-window-ctrl.js'
);
?>
<div class="rcmAdminNavigation">
    <?=
        $this->navigation('RcmAdminNavigation')
            ->menu()
            ->renderMenu(null, array('addClassToListItem' => true));
    ?>
</div>



