<div class="tabs" id="rcmTabs_<?= $this->instanceId; ?>">
    <ul class="titleWrap">
        <?php foreach ($this->instanceConfig['containers'] as $tab) {
            if (empty($tab['type'])) {
                $tab['type'] = 'html';
            }
            include 'tab-title.phtml';
        } ?>
    </ul>
    <div class="bodyWrap" style="min-height: 450px;">
        <?php foreach ($this->instanceConfig['containers'] as $tab) {

            //Fix legacy tabs that have no type
            if (empty($tab['type'])) {
                $tab['type'] = 'html';
            }

            switch ($tab['type']) {
                case 'html':
                    include 'tab-body-html.phtml';
                    break;
                case 'rawHtml':
                    include 'tab-body-raw-html.phtml';
                    break;
                default:
                    throw new \RuntimeException(
                        $tab['type'] . ' is an invalid tab type'
                    );
            }
        } ?>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#rcmTabs_<?=  $this->instanceId; ?>').tabs();
    })
</script>

