<?php
$activeTabId = null;
?>
<script src="/modules/rcm-twitter-bootstrap/bootstrap-tabcollapse/bootstrap-tabcollapse.js"
        type="text/javascript"></script>
<link href="/modules/rcm-tabs/css/styles.css" rel="stylesheet" type="text/css" />
<div class="rcmTabsContainer">

    <div role="tabpanel" class="tabs" id="rcmTabs_<?= $this->instanceId; ?>">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <?php
            foreach ($this->instanceConfig['containers'] as $key => $tab) {
                if (empty($tab['type'])) {
                    $tab['type'] = 'html';
                }
                if ($key == 0) {
                    $tab['active'] = true;
                    $activeTabId = "rcmTab_{$this->instanceId}_{$tab['id']}";
                }
                include 'tab-title.phtml';
            }
            ?>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <?php
            foreach ($this->instanceConfig['containers'] as $tab) {

                //Fix legacy tabs that have no type
                if (empty($tab['type'])) {
                    $tab['type'] = 'html';
                }
                if ($key == 0) {
                    $tab['active'] = true;
                }

                switch ($tab['type']) {
                    case 'html':
                        include 'tab-body-html.phtml';
                        break;
                    case 'rawHtml':
                        include 'tab-body-raw-html.phtml';
                        break;
                    default:
                        throw new \RuntimeException(
                            $tab['type'] . ' is an invalid tab type'
                        );
                }
            }
            ?>
        </div>
    </div>
</div>

<script type="text/javascript">

    (function () {
        var tabElm = $('#rcmTabs_<?= $this->instanceId; ?>');

        tabElm.find('[href="#<?= $activeTabId ?>"]').trigger('click');

        tabElm.tabCollapse(
            {
                <?php
                    if($this->instanceConfig['alwaysShowAccordionContent']) {
                ?>
                accordionTemplate: function(heading, groupId, parentId, active){
                    return '<div class="panel panel-default">' +
                        '   <div class="panel-heading">' +
                        '      <h4 class="panel-title">' +
                        '        <a class="" data-toggle="collapse" data-parent="#' + parentId + '" href="#' + groupId + '-NO-COLLAPSE">' +
                        '           ' + heading +
                        '        </a>' +
                        '      </h4>' +
                        '   </div>' +
                        '   <div id="' + groupId + '" class="panel-collapse collapse in">' +
                        '       <div class="panel-body js-tabcollapse-panel-body">' +
                        '       </div>' +
                        '   </div>' +
                        '</div>';
                },
                <?php
                    }
                ?>

                tabsClass: 'hidden-xs',
                accordionClass: 'visible-xs'
            }
        );
    })();

</script>
