<?php
//Setup the tabs
$lis = '';
$divs = '';

foreach ($this->ic['containers'] as $container) {
    $lis .= '<li data-containerId="'.$container['id'].'" data-containerType="'.$container['type'].'"><a href="#tab_'.$container['id'].'">';
    $lis .= '<div data-richedit="tab_title_'.$container['id'].'">';
    $lis .= $this->ic['tab_title_'.$container['id']];
    $lis .= "</div>";
    $lis .= '</a></li>';
    $divs .= '<div id="tab_'.$container['id'].'">';

    if ($container['type'] == 'html') {
        $divs .= '<div data-richedit="tab_content_'.$container['id'].'">';
        $divs .= $this->ic['tab_content_'.$container['id']];
        $divs .= "</div>";
    }

    $divs .= "</div>";
}

//print_r($this->ic);
//exit;

/**
 * RcmTabs content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 *  @category  Reliv
 *  @package   Plugins\Image
 *  @author    Rod McNew <rmcnew@relivinc.com>
 *  @copyright 2012 Reliv International
 *  @license   License.txt New BSD License
 *  @version   GIT: <git_id>
 *  @link      http://ci.reliv.com/confluence
 */
?>
<div class="rcmTabs_<?php echo $this->instanceId; ?>" style="width: 100%;">
    <ul><?php echo $lis; ?></ul>
    <?php echo $divs ?>

</div>


<script type="text/javascript">
    $(function(){
        $(".rcmTabs_<?php echo $this->instanceId; ?>").tabs();
    })
</script>
