<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmAdmin\Module' => __DIR__ . '/Module.php',
    'RcmAdmin\Controller\AdminPanelController' =>
        __DIR__ . '/src/RcmAdmin/Controller/AdminPanelController.php',
    'RcmAdmin\EventListener\DispatchListener' =>
        __DIR__ . '/src/RcmAdmin/EventListener/DispatchListener.php',
    'RcmAdmin\Factory\AdminPanelControllerFactory' =>
        __DIR__ . '/src/RcmAdmin/Factory/AdminPanelControllerFactory.php',
    'RcmAdmin\Factory\DispatchListenerFactory' =>
        __DIR__ . '/src/RcmAdmin/Factory/DispatchListenerFactory.php',
];
