<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmDialog\Module'                       => __DIR__ . '/Module.php',
    'RcmDialog\View\Helper\IncludeRcmDialog' => __DIR__ . '/src/RcmDialog/View/Helper/IncludeRcmDialog.php',
);
