<div oc-lazy-load="{name: 'pagePermissions'}">
    <div class="pagePermission">
        <div rcm-page-permissions-data="<?php echo urlencode(json_encode($data))?>"
             class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">&times;</button>
                    <h1 class="modal-title" id="myModalLabel">Page
                        Permissions</h1>
                </div>
                <div class="modal-body">
                    <div class="wrapperPagePerm">
                        <h2>Who can view this page?</h2><br>
                        <div
                            multi-select
                            input-model="roles"
                            tick-property="ticked"
                            >
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal">Close
                    </button>
                    <button type="button" ng-click="savePermissions()"
                            class="btn btn-primary saveBtn"
                            data-dismiss="modal">Save
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>