<?php
return array (
    'people' => array(
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/chrisbernard.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/chrisbernardprodreview.jpg',
            'shortDesc'=>'"I owe it all to 24 k"',
            'longDesc'=>'<strong>Name: Chris Bernard<br>Hometown: Minneapolis, MN</strong><br><strong>Current gig:</strong> Full-time student at Liberty University in Virginia, International Business Major<br><strong>Activities: </strong>Hiking, mountain biking, camping, running marathons. “Going to college near the Blue Ridge Mountains is perfect because I love being active outdoors.”<br><strong>More Focus: </strong>“My mom sent me some <a href="http://www.reliv.com/US/EN/24K-Healthy-Energy-Shot.html">24K™</a>. I drank a shot before doing my business law homework and felt more focused and clear-headed.”<br><strong>24K in training: </strong>“At a recent race, my friends asked what I was on — I finished the race faster than last year. I owe it all to 24K. I love it!” If stranded on an island with one Reliv product: “Lemon <a href="http://www.reliv.com/US/EN/Reliv-Innergize-Performance-Nutrition.html">Innergize!®</a> I love how it hydrates me and I prefer it to any other sports drink.”<br><strong>The future: </strong>“I love where Reliv is headed. After college, I might even become a Distributor!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products</span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p>'
        ),
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/paulacoffey.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/paulacoffeyprodreview.jpg',
            'shortDesc'=>'"My secret weapon!"',
            'longDesc'=>'<strong>Name: Paula Coffey<br>Hometown: Millersburg, Ohio</strong><br><strong>Reliv lifestyle:</strong> “I don’t have to wonder if we can take time off to visit family. Reliv has given us the freedom to travel whenever we want.”<br><a href="http://www.reliv.com/US/EN/Reliv-Relivables-Womens-Skincare.html"><strong>Relivables® r collection:</strong></a> “I love the r collection from Relivables! I ran into a former classmate last week. I couldn’t believe the difference in the crow’s feet around her eyes compared to mine.”<br><strong>Not-so-secret weapon:</strong> “I’m always telling people about my skincare secret weapon. My customers always want to try it — and they love it!”<br><strong>Skin nutrition:</strong> “The <a href="http://www.reliv.com/US/EN/RA7-Complex.html">RA7 complex</a> actually delivers nutrition to my skin. Not only do I feel younger, people tell me I look younger too!”<br><strong>Living the dream:</strong> “When I close my eyes and dream of the life I want to have… I already have it!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products<br></span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p><'),
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/chrisbernard.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/chrisbernardprodreview.jpg',
            'shortDesc'=>'"I owe it all to 24 k again"',
            'longDesc'=>'<strong>Again Name: Chris Bernard<br>Hometown: Minneapolis, MN</strong><br><strong>Current gig:</strong> Full-time student at Liberty University in Virginia, International Business Major<br><strong>Activities: </strong>Hiking, mountain biking, camping, running marathons. “Going to college near the Blue Ridge Mountains is perfect because I love being active outdoors.”<br><strong>More Focus: </strong>“My mom sent me some <a href="http://www.reliv.com/US/EN/24K-Healthy-Energy-Shot.html">24K™</a>. I drank a shot before doing my business law homework and felt more focused and clear-headed.”<br><strong>24K in training: </strong>“At a recent race, my friends asked what I was on — I finished the race faster than last year. I owe it all to 24K. I love it!” If stranded on an island with one Reliv product: “Lemon <a href="http://www.reliv.com/US/EN/Reliv-Innergize-Performance-Nutrition.html">Innergize!®</a> I love how it hydrates me and I prefer it to any other sports drink.”<br><strong>The future: </strong>“I love where Reliv is headed. After college, I might even become a Distributor!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products</span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p>'
        ),
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/paulacoffey.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/paulacoffeyprodreview.jpg',
            'shortDesc'=>'"My secret weapon!"',
            'longDesc'=>'<strong>Name: Paula Coffey<br>Hometown: Millersburg, Ohio</strong><br><strong>Reliv lifestyle:</strong> “I don’t have to wonder if we can take time off to visit family. Reliv has given us the freedom to travel whenever we want.”<br><a href="http://www.reliv.com/US/EN/Reliv-Relivables-Womens-Skincare.html"><strong>Relivables® r collection:</strong></a> “I love the r collection from Relivables! I ran into a former classmate last week. I couldn’t believe the difference in the crow’s feet around her eyes compared to mine.”<br><strong>Not-so-secret weapon:</strong> “I’m always telling people about my skincare secret weapon. My customers always want to try it — and they love it!”<br><strong>Skin nutrition:</strong> “The <a href="http://www.reliv.com/US/EN/RA7-Complex.html">RA7 complex</a> actually delivers nutrition to my skin. Not only do I feel younger, people tell me I look younger too!”<br><strong>Living the dream:</strong> “When I close my eyes and dream of the life I want to have… I already have it!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products<br></span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p><'),
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/chrisbernard.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/chrisbernardprodreview.jpg',
            'shortDesc'=>'"I owe it all to 24 k again"',
            'longDesc'=>'<strong>Again Name: Chris Bernard<br>Hometown: Minneapolis, MN</strong><br><strong>Current gig:</strong> Full-time student at Liberty University in Virginia, International Business Major<br><strong>Activities: </strong>Hiking, mountain biking, camping, running marathons. “Going to college near the Blue Ridge Mountains is perfect because I love being active outdoors.”<br><strong>More Focus: </strong>“My mom sent me some <a href="http://www.reliv.com/US/EN/24K-Healthy-Energy-Shot.html">24K™</a>. I drank a shot before doing my business law homework and felt more focused and clear-headed.”<br><strong>24K in training: </strong>“At a recent race, my friends asked what I was on — I finished the race faster than last year. I owe it all to 24K. I love it!” If stranded on an island with one Reliv product: “Lemon <a href="http://www.reliv.com/US/EN/Reliv-Innergize-Performance-Nutrition.html">Innergize!®</a> I love how it hydrates me and I prefer it to any other sports drink.”<br><strong>The future: </strong>“I love where Reliv is headed. After college, I might even become a Distributor!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products</span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p>'
        ),
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/paulacoffey.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/paulacoffeyprodreview.jpg',
            'shortDesc'=>'"My secret weapon!"',
            'longDesc'=>'<strong>Name: Paula Coffey<br>Hometown: Millersburg, Ohio</strong><br><strong>Reliv lifestyle:</strong> “I don’t have to wonder if we can take time off to visit family. Reliv has given us the freedom to travel whenever we want.”<br><a href="http://www.reliv.com/US/EN/Reliv-Relivables-Womens-Skincare.html"><strong>Relivables® r collection:</strong></a> “I love the r collection from Relivables! I ran into a former classmate last week. I couldn’t believe the difference in the crow’s feet around her eyes compared to mine.”<br><strong>Not-so-secret weapon:</strong> “I’m always telling people about my skincare secret weapon. My customers always want to try it — and they love it!”<br><strong>Skin nutrition:</strong> “The <a href="http://www.reliv.com/US/EN/RA7-Complex.html">RA7 complex</a> actually delivers nutrition to my skin. Not only do I feel younger, people tell me I look younger too!”<br><strong>Living the dream:</strong> “When I close my eyes and dream of the life I want to have… I already have it!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products<br></span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p><'),
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/chrisbernard.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/chrisbernardprodreview.jpg',
            'shortDesc'=>'"I owe it all to 24 k again"',
            'longDesc'=>'<strong>Again Name: Chris Bernard<br>Hometown: Minneapolis, MN</strong><br><strong>Current gig:</strong> Full-time student at Liberty University in Virginia, International Business Major<br><strong>Activities: </strong>Hiking, mountain biking, camping, running marathons. “Going to college near the Blue Ridge Mountains is perfect because I love being active outdoors.”<br><strong>More Focus: </strong>“My mom sent me some <a href="http://www.reliv.com/US/EN/24K-Healthy-Energy-Shot.html">24K™</a>. I drank a shot before doing my business law homework and felt more focused and clear-headed.”<br><strong>24K in training: </strong>“At a recent race, my friends asked what I was on — I finished the race faster than last year. I owe it all to 24K. I love it!” If stranded on an island with one Reliv product: “Lemon <a href="http://www.reliv.com/US/EN/Reliv-Innergize-Performance-Nutrition.html">Innergize!®</a> I love how it hydrates me and I prefer it to any other sports drink.”<br><strong>The future: </strong>“I love where Reliv is headed. After college, I might even become a Distributor!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products</span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p>'
        ),
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/paulacoffey.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/paulacoffeyprodreview.jpg',
            'shortDesc'=>'"My secret weapon!"',
            'longDesc'=>'<strong>Name: Paula Coffey<br>Hometown: Millersburg, Ohio</strong><br><strong>Reliv lifestyle:</strong> “I don’t have to wonder if we can take time off to visit family. Reliv has given us the freedom to travel whenever we want.”<br><a href="http://www.reliv.com/US/EN/Reliv-Relivables-Womens-Skincare.html"><strong>Relivables® r collection:</strong></a> “I love the r collection from Relivables! I ran into a former classmate last week. I couldn’t believe the difference in the crow’s feet around her eyes compared to mine.”<br><strong>Not-so-secret weapon:</strong> “I’m always telling people about my skincare secret weapon. My customers always want to try it — and they love it!”<br><strong>Skin nutrition:</strong> “The <a href="http://www.reliv.com/US/EN/RA7-Complex.html">RA7 complex</a> actually delivers nutrition to my skin. Not only do I feel younger, people tell me I look younger too!”<br><strong>Living the dream:</strong> “When I close my eyes and dream of the life I want to have… I already have it!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products<br></span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p><'),
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/chrisbernard.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/chrisbernardprodreview.jpg',
            'shortDesc'=>'"I owe it all to 24 k again"',
            'longDesc'=>'<strong>Again Name: Chris Bernard<br>Hometown: Minneapolis, MN</strong><br><strong>Current gig:</strong> Full-time student at Liberty University in Virginia, International Business Major<br><strong>Activities: </strong>Hiking, mountain biking, camping, running marathons. “Going to college near the Blue Ridge Mountains is perfect because I love being active outdoors.”<br><strong>More Focus: </strong>“My mom sent me some <a href="http://www.reliv.com/US/EN/24K-Healthy-Energy-Shot.html">24K™</a>. I drank a shot before doing my business law homework and felt more focused and clear-headed.”<br><strong>24K in training: </strong>“At a recent race, my friends asked what I was on — I finished the race faster than last year. I owe it all to 24K. I love it!” If stranded on an island with one Reliv product: “Lemon <a href="http://www.reliv.com/US/EN/Reliv-Innergize-Performance-Nutrition.html">Innergize!®</a> I love how it hydrates me and I prefer it to any other sports drink.”<br><strong>The future: </strong>“I love where Reliv is headed. After college, I might even become a Distributor!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products</span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p>'
        ),
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/paulacoffey.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/paulacoffeyprodreview.jpg',
            'shortDesc'=>'"My secret weapon!"',
            'longDesc'=>'<strong>Name: Paula Coffey<br>Hometown: Millersburg, Ohio</strong><br><strong>Reliv lifestyle:</strong> “I don’t have to wonder if we can take time off to visit family. Reliv has given us the freedom to travel whenever we want.”<br><a href="http://www.reliv.com/US/EN/Reliv-Relivables-Womens-Skincare.html"><strong>Relivables® r collection:</strong></a> “I love the r collection from Relivables! I ran into a former classmate last week. I couldn’t believe the difference in the crow’s feet around her eyes compared to mine.”<br><strong>Not-so-secret weapon:</strong> “I’m always telling people about my skincare secret weapon. My customers always want to try it — and they love it!”<br><strong>Skin nutrition:</strong> “The <a href="http://www.reliv.com/US/EN/RA7-Complex.html">RA7 complex</a> actually delivers nutrition to my skin. Not only do I feel younger, people tell me I look younger too!”<br><strong>Living the dream:</strong> “When I close my eyes and dream of the life I want to have… I already have it!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products<br></span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p><'),
        array(
            'smallImage'=>'http://content.reliv.com/editor/image/chrisbernard.jpg',
            'largeImage'=>'http://content.reliv.com/editor/image/chrisbernardprodreview.jpg',
            'shortDesc'=>'"I owe it all to 24 k again"',
            'longDesc'=>'<strong>Again Name: Chris Bernard<br>Hometown: Minneapolis, MN</strong><br><strong>Current gig:</strong> Full-time student at Liberty University in Virginia, International Business Major<br><strong>Activities: </strong>Hiking, mountain biking, camping, running marathons. “Going to college near the Blue Ridge Mountains is perfect because I love being active outdoors.”<br><strong>More Focus: </strong>“My mom sent me some <a href="http://www.reliv.com/US/EN/24K-Healthy-Energy-Shot.html">24K™</a>. I drank a shot before doing my business law homework and felt more focused and clear-headed.”<br><strong>24K in training: </strong>“At a recent race, my friends asked what I was on — I finished the race faster than last year. I owe it all to 24K. I love it!” If stranded on an island with one Reliv product: “Lemon <a href="http://www.reliv.com/US/EN/Reliv-Innergize-Performance-Nutrition.html">Innergize!®</a> I love how it hydrates me and I prefer it to any other sports drink.”<br><strong>The future: </strong>“I love where Reliv is headed. After college, I might even become a Distributor!”</p><p>&nbsp;</p><p><a href="http://www.reliv.com/US/EN/custcontact.html"><span class="smOrderNowLink">Order Products</span></a></p><p><a href="http://www.reliv.com/US/EN/Tell-Your-Story.html"><span class="smOrderNowLink">Tell us your story!</span></a></p>'
        )
    )
);