<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmLogin\Controller\PluginController' => __DIR__ . '/src/RcmLogin/Controller/PluginController.php',
  'RcmLogin\Module'                      => __DIR__ . '/Module.php',
);
