<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmLogin\Module' => __DIR__ . '/Module.php',
    'RcmLogin\Controller\PluginController' =>
        __DIR__ . '/src/RcmLogin/Controller/PluginController.php',
    'RcmLogin\Factory\PluginControllerFactory' =>
        __DIR__ . '/src/RcmLogin/Factory/PluginControllerFactory.php',
];
