<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmJquery\Module' => __DIR__ . '/Module.php',
    'RcmJquery\Factory\IncludeJqueryFactory' =>
        __DIR__ . '/src/RcmJquery/Factory/IncludeJqueryFactory.php',
    'RcmJquery\View\Helper\IncludeJquery' =>
        __DIR__ . '/src/RcmJquery/View/Helper/IncludeJquery.php',
    'RcmJqueryTest\IncludeJqueryViewHelperTest' =>
        __DIR__ . '/test/RcmJquery/Factory/IncludeJqueryViewHelperTest.php',
    'RcmJqueryTest\IncludeJqueryTest' =>
        __DIR__ . '/test/RcmJquery/View/Helper/IncludeJqueryTest.php',
];
