<a href="<?= $this->escapeHtml($this->instanceConfig['href']) ?>">
    <div class="rollImg" style="background-image: url('<?= $this->escapeHtml($this->instanceConfig['imageSrc']) ?>')"></div>
    <?=
    $this->rcmTextEdit(
        'top',
        'Discover',
        'div',
        ['class' => 'top']
    ) ?>
    <?=
    $this->rcmTextEdit(
        'bottom',
        'Discover the greatness and grandeur of the call to action box plugin',
        'div',
        ['class' => 'bottom']
    ) ?>
    <?=
    $this->rcmTextEdit(
        'readMore',
        'READ MORE',
        'div',
        ['class' => 'readMore']
    ) ?>
</a>


