<?php

/**
 * RcmCallToActionBox content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-call-to-action-box/style.css'
);

?>

<!--<span data-textEdit="newTestVal">-->
<!--    --><?php //echo $this->ic['newTestVal']; ?>
<!--</span>-->

<div>


    <h1>
        <a href="<?php echo $this->ic['href']?>">
            <span data-textEdit="top">
                <?php echo $this->ic['top']; ?>
            </span>
        </a>
    </h1>


    <h2>
        <a href="<?php echo $this->ic['href']?>">
            <span data-textEdit="middle">
           <?php echo $this->ic['middle']; ?>
            </span>
        </a>
    </h2>

    <p data-textEdit="bottom">
        <?php echo $this->ic['bottom']?>
    </p>

    <img alt="<?php echo $this->ic['top']?>"
         class="bg"
         src="<?php echo
             $this->getContentBasePath() . $this->ic['imageSrc']?>"
        >

</div>


