<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmDjPluginStorage\Controller\BasePluginController'         => __DIR__ . '/src/RcmDjPluginStorage/Controller/BasePluginController.php',
    'RcmDjPluginStorage\Entity\InstanceConfig'                   => __DIR__ . '/src/RcmDjPluginStorage/Entity/InstanceConfig.php',
    'Bootstrap'                                                  => __DIR__ . '/test/Bootstrap.php',
    'RcmDjPluginStorageTest\Controller\BasePluginControllerTest' => __DIR__ . '/test/RcmDjPluginStorageTest/Controller/BasePluginControllerTest.php',
    'RcmDjPluginStorageTest\Entity\InstanceConfigTest'           => __DIR__ . '/test/RcmDjPluginStorageTest/Entity/InstanceConfigTest.php',
    'RcmDjPluginStorageTest\ModuleTest'                          => __DIR__ . '/test/RcmDjPluginStorageTest/ModuleTest.php',
    'RcmDjPluginStorage\Module'                                  => __DIR__ . '/Module.php',
);