<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmDJPluginStorage\Controller\BasePluginController'            => __DIR__ . '/src/RcmDJPluginStorage/Controller/BasePluginController.php',
    'RcmDJPluginStorage\StorageEngine\DoctrineSerializedRepo'       => __DIR__ . '/src/RcmDJPluginStorage/StorageEngine/DoctrineSerializedRepo.php',
    'RcmDJPluginStorage\Exception\RuntimeException'                 => __DIR__ . '/src/RcmDJPluginStorage/Exception/RuntimeException.php',
    'RcmDJPluginStorage\Exception\PluginDataNotFoundException'      => __DIR__ . '/src/RcmDJPluginStorage/Exception/PluginDataNotFoundException.php',
    'RcmDJPluginStorage\Entity\InstanceConfig'                      => __DIR__ . '/src/RcmDJPluginStorage/Entity/InstanceConfig.php',
    'Bootstrap'                                                         => __DIR__ . '/test/Bootstrap.php',
    'RcmDJPluginStorage\Module\Controller\BasePluginControllerTest' => __DIR__ . '/test/RcmDJPluginStorageTest/Controller/BasePluginControllerTest.php',
    'RcmDJPluginStorage\Module'                                     => __DIR__ . '/Module.php',
);