<?php

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-dynamic-navigation/vendor/superfish/dist/js/hoverIntent.js',
    'text/javascript'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-dynamic-navigation/vendor/superfish/dist/js/superfish.js',
    'text/javascript'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-dynamic-navigation/rcm-dynamic-navigation.js',
    'text/javascript'
);

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-dynamic-navigation/vendor/superfish/dist/css/superfish.css'
);

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-dynamic-navigation/rcm-dynamic-navigation.css'
);

function getUl($data, $id=null)
{
?>
    <ul class="<?php if (!empty($id)) : ?>sf-menu" id="<?= $id; ?><?php endif; ?>">
            <?php foreach ($data as $link) {getLi($link);} ?>
    </ul>
<?php
}

function getLi($link)
{
    if (empty($link['class'])) { $link['class'] = ''; }
    if (empty($link['system_class'])) { $link['system_class'] = ''; }
    if (empty($link['href'])) { $link['href'] = ''; }
    if (empty($link['target'])) { $link['target'] = ''; }
    if (empty($link['display'])) { $link['display'] = ''; }
    if (empty($link['permissions'])) { $link['permissions'] = ''; }

?>
        <li class="<?= $link['class']?> <?= $link['system_class']?>" data-class="<?= $link['class']?>" data-permissions="<?= $link['permissions'] ?>">
            <a href="<?= $link['href']?>" <?php if (!empty($link['target'])) { ?> target="<?= $link['target']; ?>"<?php } ?>>
                <?= $link['display']; ?>
            </a>

            <?php if (!empty($link['links']) && is_array($link['links'])) { getUl($link['links']); } ?>
        </li>
<?php
}


getUl($this->instanceConfig['links'], "RcmDynamicNavigation_".$this->instanceId);
