<?php

/**
 * Visitor-facing plugin template
 *
 * Visitor-facing plugin template
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 */
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-navigation/style.css'
);
?>
<ul>
    <?= $this->instanceConfig['html'] ?>
</ul>