<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
  'RcmLib\Module'                        => __DIR__ . '/Module.php',
  'RcmLib\Controller\TestController'     => __DIR__ . '/src/RcmLib/Controller/TestController.php',
  'RcmLib\View\Helper\IncludeHtmlEditor' => __DIR__ . '/src/RcmLib/View/Helper/IncludeHtmlEditor.php',
];
