<script type="text/javascript">

    function myTemplateLoaded<?php echo $this->instanceId; ?>(evt) {
        bgPlayerApi<?php echo $this->instanceId; ?>.myTemplateLoaded(evt);
    }

    function onTemplateReady<?php echo $this->instanceId; ?>(evt) {
        bgPlayerApi<?php echo $this->instanceId; ?>.onTemplateReady(evt);
    }
</script>
<script type="text/javascript">
    var bgPlayerApi<?= $this->instanceId; ?> = new brightcovePlayerApi(<?= $this->instanceId; ?>);
</script>
<div class="hide-vid">
    <div style="float: right;"><a
            id="RcmBrightcovePlayerDownloadLink<?= $instanceId ?>"
            data-textEdit="download"><?= $this->instanceConfig['download']; ?></a>
    </div>
    <br>
    <br>
    <div ng-controller="playerTabsCtrl"
         ng-init="init(<?=
         json_encode(
             $instanceConfig['playlistIds']
         ); ?>,<?php echo $this->instanceId; ?>)">
        <script type="text/javascript"
                src="/modules/rcm-brightcove-player/vendor/brightcove/BrightcoveExperiences.js"></script>
        <div id="downloadLink"></div>
        <div data-hbo-tabs id="rcm-brightcove-player-tabs">
            <div id="player" align="center">
                <!-- Start of Brightcove Player -->
                <script language="JavaScript" type="text/javascript"
                        src="https://sadmin.brightcove.com/js/BrightcoveExperiences.js"></script>
                <object id="myExperience" class="BrightcoveExperience">
                    <param name="bgcolor" value="#FFFFFF"/>
                    <param name="width" value="672"/>
                    <param name="height" value="378"/>
                    <param name="playerID" value="2660464878001"/>
                    <param name="playerKey"
                           value="AQ~~,AAABWA8lTok~,NLWj-wltGTxQtoAwLzwEdE62BFMU_8At"/>
                    <param name="isVid" value="true"/>
                    <param name="isUI" value="true"/>
                    <param name="wmode" value="opaque"/>
                    <param name="dynamicStreaming" value="true"/>
                    <param name="includeAPI" value="true"/>
                    <param name="secureConnections" value="true"/>
                    <param name="secureHTMLConnections" value="true"/>
                    <param name="templateLoadHandler"
                           value="myTemplateLoaded<?php echo $this->instanceId; ?>"/>
                    <param name="templateReadyHandler"
                           value="onTemplateReady<?php echo $this->instanceId; ?>"/>
                </object>
            </div>


            <ul>
                <li ng-repeat="(key,playlist) in playlists"><a
                        href="#tabs-{{key}}">{{playlist.name}}</a></li>
            </ul>

            <div
                class="videoAreaWrap"
                id="tabs-{{key}}"
                ng-repeat="(key,playlist) in playlists"
                >
                <div ng-repeat="video in playlist.videos">
                    <a href="javascript:void(0);"
                       ng-click="videoClick()"
                       class="videoArea"
                        >
                        <table>
                            <tr>
                                <td style="text-align: left;">
                                    <img ng-src="{{video.thumbnailURL}}"
                                         width="135px" height="70px"/>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                <span class="title">
                                    <p style="text-decoration: none; color: #00a4e4; font-weight: bold; font-size: 10px;">
                                        {{video.name}}</p></span>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                <span class="description"><p
                                        style="text-decoration: none;font-size: 10px;">
                                        {{video.shortDescription}}</p></span>
                                </td>
                            </tr>
                        </table>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


