<?php

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-brightcove-player/style.css'
);
$this->headScript()->appendFile(
    $this->basePath() . 'https://sadmin.brightcove.com/js/BrightcoveExperiences.js'
);
?>
<!-- <RcmBrightcovePlayer> -->
<div>
    <script>
        RcmBrightcoveApiService.bgReadToken = '<?= $config['rcmPlugin']['RcmBrightcovePlayer']['readToken']; ?>';
        RcmBrightcoveApiService.bgUrlToken = '<?= $config['rcmPlugin']['RcmBrightcovePlayer']['urlToken']; ?>';
        RcmBrightcovePlayerService.instantiatePlayerController(<?= htmlentities($instanceId)?>, <?=json_encode($instanceConfig)?>);
    </script>
    <?php

    if (($instanceConfig['type']) == 'single-embed') {
        require('single_player.phtml');
    } elseif (($instanceConfig['type']) == 'multi-embed') {
        require('multi-player.phtml');
    }

    // @todo this should only be loaded as needed
    require('plugin-edit.phtml');

    ?>
</div>
<!-- <RcmBrightcovePlayer> -->





