<div style="display:none">
    <div rcm-brightcove-player-edit="<?= $instanceId ?>">
        <form style="display:none"
              title="Brightcove Player Editor"
              novalidate
              class="RcmBrightcovePlayer"
            >

            <div>
                <div>
                    <select name="type">
                        <option value="single-embed">
                            Single Video Player
                        </option>
                        <option value="multi-embed">
                            Multi-Video Player With Tabs
                        </option>
                    </select>
                </div>
                <div class="single-embed-options">

                    <br/>Choose video:<br/>
                    <select name="video"></select>
                    <br><br>
                    <img class="thumbnailPreview"/>
                    <br/>
                </div>
                <div class="multi-embed-options">
                    <br/><br/>

                    <div rcm-brightcove-player-edit-multi-select></div>
                </div>
            </div>
            <br/>

            <div style="clear:both;"></div>
        </form>
    </div>
</div>






