<?php

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-brightcove-player/jquery-model/jquery.brightcove.js',
    'text/javascript'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-brightcove-player/rcm-brightcove-player.js',
    'text/javascript'
);

//$this->headLink()->appendStylesheet(
//    $this->basePath() . '/modules/rcm-brightcove-player/style.css'
//);
// ng-switch-when="{{solution.title}}
?>

<div style="display:none;">
    <form id="brightcoveform" title="Brightcove Player Editor">

        <div  ng-controller="BrightcoveCtrl">
            <div>
                <div ng-show="true">
                    <select
                        ng-model="selectedItem"
                        ng-init="selectedItem = selectedItem || items[0]"
                        ng-options="item as item.name for item in items">
                    </select>
                </div>
                <div ng-show="selectedItem.id == 0"}>
                    <br>Choose video:<br>
                    <select
                        ng-options="video.name for video in videos"
                        ng-model="selectedVideos">
                    </select>
                    {{selectedVideos.name}}
                    <br>
                    {{selectedVideos.id}}
                    <br>
                    <img src="{{selectedVideos.thumbnailURL}}" />
                    <br>
                </div>

                <div ng-show="selectedItem.id == 1">
                    <br>Choose Playlist:<br>
                    <select
                         ng-options="playlist.name for playlist in playlists"
                         ng-model="selectedPlaylists"
                         multiselect-dropdown>
                    </select>
                    <br>
                    {{selectedPlaylists.name}}
                </div>
                <br>
                <button ng-click="update(video)">save</button>
                <div><br></div>
            </div>
        </div>
    </form>
</div>

