<?php

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-brightcove-player/jquery-model/jquery.brightcove.js',
    'text/javascript'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-brightcove-player/rcm-brightcove-player.js',
    'text/javascript'
);

//$this->headLink()->appendStylesheet(
//    $this->basePath() . '/modules/rcm-brightcove-player/style.css'
//);
// ng-switch-when="{{solution.title}}
?>

<div ng-controller="BrightcoveCtrl">

    <!-- Start of Brightcove Player -->

    <div style="display:none">

    </div>

    <!--
    By use of this code snippet, I agree to the Brightcove Publisher T and C
    found at https://accounts.brightcove.com/en/terms-and-conditions/.
    -->

    <script language="JavaScript" type="text/javascript" src="http://admin.brightcove.com/js/BrightcoveExperiences.js"></script>

    <object id="myExperience<?= $ic['videoId'] ?>" class="BrightcoveExperience">
        <param name="bgcolor" value="#FFFFFF" />
        <param name="width" value="400" />
        <param name="height" value="225" />
        <param name="playerID" value="2660464886001" />
        <param name="playerKey" value="AQ~~,AAABWA8lTok~,NLWj-wltGTwPRfYtwg9pVEh-A2jBVrQE" />
        <param name="isVid" value="true" />
        <param name="isUI" value="true" />
        <param name="dynamicStreaming" value="true" />

        <param name="@videoPlayer" value="<?= $ic['videoId'] ?>" />
    </object>

    <!--
    This script tag will cause the Brightcove Players defined above it to be created as soon
    as the line is read by the browser. If you wish to have the player instantiated only after
    the rest of the HTML is processed and the page load is complete, remove the line.
    -->
    <script type="text/javascript">brightcove.createExperiences();</script>

    <!-- End of Brightcove Player -->


    <form style="display:none" title="Brightcove Player Editor" novalidate >

        <div>
            <div>
                <div ng-show="true">
                    <select
                        ng-model="selectedItem"
                        ng-init="selectedItem = selectedItem || items[0]"
                        ng-options="item as item.name for item in items">
                    </select>
                </div>
                <div ng-show="selectedItem.id == 0"}>
                    <br>Choose video:<br>
                    <select
                        name="video"
                        ng-model="selectedVideos"
                        ng-init="selectedVideos = selectedVideos || videos[0]"
                        ng-options="video.name for video in videos">
                    </select>
<!--                    {{selectedVideos.name}} -->
                    <br>
<!--                    {{selectedVideos.id}}  -->
                    <br>
                <img src="{{selectedVideos.thumbnailURL}}" />
                    <br>
                </div>
                <div ng-show="selectedItem.id == 1">
                    <br>Choose Playlist:<br>
                    <select
                         ng-options="playlist.name for playlist in playlists"
                         ng-model="selectedPlaylists">
                    </select>
                    <br>
                         {{selectedPlaylists.videoIds}}
                </div>
                <br>
                <div><br></div>
            </div>
        </div>
    </form>
</div>

