<script type="text/javascript">

    getDownloadURL(
        <?= json_encode($ic['videoId']); ?>,
        function (url) {
            $('#RcmBrightcovePlayerDownloadLink<?= $instanceId ?>').attr('href', url);
        }
    );
</script>
<div class="hide-vid" style="border:0">
    <div style="float: right;"><a id="RcmBrightcovePlayerDownloadLink<?= $instanceId ?>"
                                  data-textEdit="download"><?= $this->ic['download']; ?></a></div>
    <br>

    <!-- Start of Brightcove Player -->

    <div style="display:none"></div>

    <!--
    By use of this code snippet, I agree to the Brightcove Publisher T and C
    found at https://accounts.brightcove.com/en/terms-and-conditions/.
    -->
    <br>
    <script language="JavaScript" type="text/javascript"
            src="/modules/rcm-brightcove-player/vendor/brightcove/BrightcoveExperiences.js"></script>
    <div id="brightcoveObject">
        <object id="myExperience<?= $ic['videoId'] ?>" class="BrightcoveExperience">
            <param name="bgcolor" value="#FFFFFF"/>
            <param name="width" value="672"/>
            <param name="height" value="378"/>
            <param name="playerID" value="2660464878001"/>
            <param name="playerKey" value="AQ~~,AAABWA8lTok~,NLWj-wltGTxQtoAwLzwEdE62BFMU_8At"/>
            <param name="isVid" value="true"/>
            <param name="isUI" value="true"/>
            <param name="dynamicStreaming" value="true"/>
            <param name="mute" value="true"/>

            <param name="@videoPlayer" value="<?= $ic['videoId'] ?>"/>
        </object>
    </div>
    <br><br><br><br>
    <!--
    This script tag will cause the Brightcove Players defined above it to be created as soon
    as the line is read by the browser. If you wish to have the player instantiated only after
    the rest of the HTML is processed and the page load is complete, remove the line.
    -->
    <script type="text/javascript">brightcove.createExperiences();</script>

    <!-- End of Brightcove Player -->

</div>
