<!-- <brightcovePlayerSingle> -->
<div class="hide-vid" style="border:0">
    <div style="float: right;" rcm-brightcove-player-download-link="<?= $instanceId ?>">
        <?= $instanceConfig['download'] ?>
    </div>
    <div style="clear: both"></div>
    <div class="video"
         id="brightcoveObject"
         rcm-brightcove-player="<?= $instanceId ?>"
         style="padding-bottom: <?= number_format($aspectHeight, 2, '.', ''); ?>%;"
    >
        <div class="placeholder">
            VIDEO PLAYER
        </div>
    </div>
</div>
<!-- </brightcovePlayerSingle> -->