<?php

/**
 * RcmPeopleSlider content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 */
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-people-slider/style.css'
);
$this->headScript()->appendFile(
    $this->basePath()
        . '/modules/rcm/vendor/aperture-slider/aperture-slider.js',
    'text/javascript'
);
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-people-slider/rcm-people-slider.js',
    'text/javascript'
);

//Figure out which person we are viewing. This non-js support is only for SEO.
$selectedPersonId = 0;
if (!empty($_GET['id']) && $_GET['id'] < count($this->ic['people'])) {
    $selectedPersonId = $_GET['id'];
}

$selectedPerson = $this->ic['people'][$selectedPersonId];

$uriParts=explode('?', $_SERVER['REQUEST_URI']);
$currentUrl = '//' . $_SERVER['HTTP_HOST'] . $uriParts[0];
?>
<script type="text/javascript">
    $(function () {
        new RcmPeopleSlider(
        <?=  $this->instanceId?>,
        <?=  json_encode($this->ic)?>
        );
    });
</script>
<div>

    <div class="peopleDetails"
         data-selectedPersonId="<?=  $selectedPersonId?>">
        <?php //person output here for non-js support for SEO reasons only ?>
        <table class="personDetails">
            <tr>
                <td>
                    <div class="longDesc">
                        <?=  $selectedPerson['longDesc']?>
                    </div>
                </td>
                <td>
                    <img class="largeImage"
                         src="<?=  $selectedPerson['largeImage']?>">
                </td>
            </tr>
        </table>
    </div>

    <br>

    <div class="peopleBorder">

        <div class="left arrow">&nbsp;</div>

        <div class="peopleAperture">
            <div class="previews">
                <?php foreach ($this->ic['people'] as $personId => $person): ?>
                <?php
                $classAppend = null;
                if ($personId == $selectedPersonId) {
                    $classAppend = ' selected';
                }
                ?>
                <a href="<?=  "$currentUrl?id=$personId" //for SEO ?>"
                   class="person<?=  $classAppend ?>"
                   data-personId="<?=  $personId?>">
                   <img class="smallImage"
                         src="<?=  $person['smallImage']?>">

                    <div class="shortDesc"><?=  $person['shortDesc']?></div>
                </a>
                <?php endforeach?>
            </div>
        </div>

        <div class="right arrow">&nbsp;</div>

    </div>

</div>

