<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmEventCalenderCore\Module' => __DIR__ . '/Module.php',
    'RcmEventCalenderCore\Controller\AbstractAPIController' => __DIR__
        . '/src/RcmEventCalenderCore/Controller/AbstractAPIController.php',
    'RcmEventCalenderCore\Controller\CategoryAPIController' => __DIR__
        . '/src/RcmEventCalenderCore/Controller/CategoryAPIController.php',
    'RcmEventCalenderCore\Controller\EventAPIController' =>
        __DIR__ . '/src/RcmEventCalenderCore/Controller/EventAPIController.php',
    'RcmEventCalenderCore\Entity\Category' =>
        __DIR__ . '/src/RcmEventCalenderCore/Entity/Category.php',
    'RcmEventCalenderCore\Entity\Event' =>
        __DIR__ . '/src/RcmEventCalenderCore/Entity/Event.php',
    'RcmEventCalenderCore\Exception\ExceptionInterface' =>
        __DIR__ . '/src/RcmEventCalenderCore/Exception/ExceptionInterface.php',
    'RcmEventCalenderCore\Exception\InvalidArgumentException' => __DIR__
        . '/src/RcmEventCalenderCore/Exception/InvalidArgumentException.php',
    'RcmEventCalenderCore\Model\Calender' =>
        __DIR__ . '/src/RcmEventCalenderCore/Model/Calender.php',
];
