<div>
    <div>
        <?=
        $this->rcmRichEdit(
            'title',
            $this->instanceConfig['title'],
            'h2'
        ); ?>
    </div>
    <div>
        <?php
        echo $this->rcmMessageUserMessageList(
            $this->instanceConfig['source'],
            $this->instanceConfig['level'],
            $this->instanceConfig['hasViewed']
        );
        ?>
    </div>
</div>