<?php

/**
 * Visitor-facing plugin template
 *
 * Visitor-facing plugin template
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 */
$this->headLink()->appendStylesheet(
    $this->basePath()
    . '/modules/rcm-nav-responsive/vendor/superfish/dist/css/superfish.css'
);
$this->headLink()->appendStylesheet(
    $this->basePath()
    . '/modules/rcm-nav-responsive/style.css'
);
$this->headScript()->appendFile(
    $this->basePath()
    . '/modules/rcm-nav-responsive/vendor/jquery.mobilemenu.js',
    'text/javascript'
);
$this->headScript()->appendFile(
    $this->basePath()
    . '/modules/rcm-nav-responsive/vendor/superfish/dist/js/hoverIntent.js',
    'text/javascript'
);
$this->headScript()->appendFile(
    $this->basePath()
    . '/modules/rcm-nav-responsive/vendor/superfish/dist/js/superfish.min.js',
    'text/javascript'
);
?>
<script>
    $(function () {
        $('.RcmNavResponsive ul.sf-menu').superfish({speed: 1});
        $('.RcmNavResponsive select').change(
            function () {
                window.location.href = $(this).val();
            }
        );
    });
</script>
<nav>
    <ul class="sf-menu">
        <?php foreach ($instanceConfig['children'] as $link): ?>
            <li>
                <a class="sf-with-ul"
                   href="<?= $this->escapeHtmlAttr($link['href']) ?>">
                    <?= $this->escapeHtml($link['text']) ?>
                </a>
                <ul class="submenu">
                    <?php foreach ($link['children'] as $childLink): ?>
                        <li>
                            <a href="<?=
                            $this->escapeHtmlAttr($childLink['href'])
                            ?>">
                                <?= $this->escapeHtml($childLink['text']) ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </li>
        <?php endforeach ?>
    </ul>
</nav>
<select>
    <option selected value="#">
        <?= $this->translate('Select a page:') ?>
    </option>
    <?php foreach ($instanceConfig['children'] as $link): ?>
        <option value="<?= $this->escapeHtmlAttr($link['href']) ?>">
            <?= $this->escapeHtml($link['text']) ?>
        </option>
        <?php foreach ($link['children'] as $childLink): ?>
            <option
                value="<?= $this->escapeHtmlAttr($childLink['href']) ?>">
                - <?= $this->escapeHtml($childLink['text']) ?>
            </option>
        <?php endforeach ?>
    <?php endforeach ?>
</select>