<?php

/**
 * RcmGoogleSearchBox content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 */
$this->headScript()->appendFile(
    $this->basePath()
    . '/modules/rcm-google-search-box/rcm-google-search-box.js',
    'text/javascript'
);
$qq = isset($_GET['qq']) ? $_GET['qq'] : null;
?>
<script type="text/javascript">
    $(
        function () {
            new RcmGoogleSearchBox(
                <?= json_encode($this->instanceId)?>
            );
        }
    );
</script>
<form action="<?= $this->instanceConfig['resultPage'] ?>">

    <div class="searchField">
        <input type="hidden"
               name="cx"
               value="<?= $this->instanceConfig['googleKey'] ?>"/>
        <input type="hidden"
               name="ie"
               value="UTF-8"/>
        <input type="hidden"
               name="q"/>
        <input value="<?= $this->escapeHtml($qq) ?>"
               type="text"
               name="qq"
               size="40"/>
    </div>
    <div class="searchButton">
        <button class="glyphicon glyphicon-search plain search">
            <span>Search</span>
        </button>
    </div>
</form>

