<?php

/**
 * RcmGoogleSearchBox content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 */
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-google-search-box/rcm-google-search-box.js',
    'text/javascript'
);
$qq=isset($_GET['qq'])?$_GET['qq']:null;
?>
<script type="text/javascript">
    $(function () {
        new RcmGoogleSearchBox(
            <?=  $this->instanceId?>
        );
    });
</script>
<form action="<?=  $this->ic['resultPage']?>">
    <input type="hidden" name="cx" value="<?=  $this->ic['googleKey']?>">
    <input type="hidden" name="ie" value="UTF-8">
    <input type="hidden" name="q">
    <input value="<?=  $this->escapeHtml($qq) ?>" type="text" name="qq" size="40">

    <button class="plain search">Search</button>

</form>

