<?php
namespace RcmNavigation\Controller;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-05 at 13:19:28.
 */
class PluginControllerTest extends \Rcm\Base\BaseTest
{
    /**
     * @var PluginController
     */
    protected $unit;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->unit = new PluginController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}
