<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmEventListDisplay\Module' => __DIR__ . '/Module.php',
    'RcmEventListDisplay\Controller\PluginController' =>
        __DIR__ . '/src/RcmEventListDisplay/Controller/PluginController.php',
];
