<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmEventListDisplay\Controller\PluginController' => __DIR__ . '/src/RcmEventListDisplay/Controller/PluginController.php',
  'RcmEventListDisplay\Module'                      => __DIR__ . '/Module.php',
);
