<!-- <brightcovePlayerMulti> -->

<script src="/modules/rcm-twitter-bootstrap/bootstrap-tabcollapse/bootstrap-tabcollapse.js"
        type="text/javascript"></script>
<div class="hide-vid">
    <div style="float: right;"
         rcm-brightcove-player-download-link="<?= $instanceId ?>" >
    </div>
    <div style="clear: both"></div>
    <br/>

    <div class="ui-tabs ui-widget ui-widget-content ui-corner-all">
        <div id="downloadLink"></div>

        <div class="video"
             id="brightcoveObject"
             data-keep-aspect-ratio="<?= $instanceConfig['aspectRatio'] ?>"
             rcm-brightcove-player="<?= $instanceId ?>"><div style="background-color: #000000; width: 100%; height: 100%">VIDEO PLAYER</div>
        </div>

        <div role="tabpanel" rcm-brightcove-player-tabs="<?= $instanceId ?>" class="tabs">
            <div class="rcm-brightcove-player-tabs-wrapper">
                <ul class="nav nav-tabs rcmBrightcovePlayerTabs" role="tablist" data-tabs="tabs" ng-style="isHide()"></ul>
                <div class="tab-content"></div>
            </div>
        </div>
    </div>
</div>
<!-- </brightcovePlayerMulti> -->
