<div style="display:none">
    <div rcm-brightcove-player-edit="<?= $instanceId ?>">
        <form style="display:none"
              title="Brightcove Player Editor"
              novalidate
              class="RcmBrightcovePlayer"
            >

            <div>
                <div>
                    <label>
                        Single Video or Multi Video:<br>
                        <select name="type">
                            <option value="single-embed">
                                Single Video Player
                            </option>
                            <option value="multi-embed">
                                Multi-Video Player With Tabs
                            </option>
                        </select>
                    </label>
                    <br>
                    <label>
                        Aspect Ratio:<br>
                        <select name="aspectRatio">
                            <option value="16:9">
                                16:9 Standard
                            </option>
                            <option value="2.35:1">
                                2.35:1 Widescreen
                            </option>
                        </select>
                    </label>
                </div>
                <div class="single-embed-options">
                    Choose Video:<br/>
                    <select name="video"></select>
                    <br><br>
                    <img class="thumbnailPreview"/>
                    <br/>
                </div>
                <div class="multi-embed-options">
                    <br/><br/>

                    <div rcm-brightcove-player-edit-multi-select></div>
                </div>
            </div>
            <br/>

            <div style="clear:both;"></div>
        </form>
    </div>
</div>






