<?php

$this->rcmJsLibIncludeCoreJs();
$this->rcmIncludeJqueryUi();
$this->rcmIncludeTwitterBootstrap();

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-tinymce-js/tinymce/tinymce.js'
);
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-js-lib/rcm-html-editor/rcm-html-editor.js'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-admin/js/rcm-admin.js'
);

$this->headLink()->appendStylesheet(
    '/modules/rcm-js-lib/rcm-html-editor/rcm-html-editor.css'
);

?>

<?= $this->render('rcm-admin/admin/partial/panel/panel.phtml'); ?>
<?= $this->render('rcm-admin/admin/partial/dialog/dialog.phtml'); ?>
