<?php
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-admin/css/rcm-admin-navigation.css',
    'screen,print'
);

?>

<div id="rcmAdminNavigation" ng-controller="rcmAdminNavigationController">
    <ul>
        <li data-ng-repeat="menuItem in adminToolBar" data-ng-include="'node_template.html'"></li>
    </ul>

    <script type="text/ng-template" id="node_template.html">
        {{menuItem.display}}
        <ul><li data-ng-repeat = "menuItem in menuItem.links"
                data-ng-include = "'node_template.html'" ></li>
        </ul>
    </script>
</div>

<div style="clear: both;"></div>

<script type="text/javascript">
    angular.module('rcmAdminNavigation', []);

    angular.module('rcmAdminNavigation').service('AdminMenu', function(){
            this.menuItems = <?= json_encode($this->adminMenu); ?>;
    });

    angular.module('rcmAdminNavigation').controller('rcmAdminNavigationController', ['$scope', 'AdminMenu', function($scope, AdminMenu) {
        $scope.adminToolBar = AdminMenu.menuItems;
        console.log(AdminMenu.menuItems);
    }]);

    angular.element(document).ready(function() {
        angular.bootstrap(document.getElementById('rcmAdminNavigation'), ['rcmAdminNavigation']);
    });
</script>