<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmRssFeed\Controller\ProxyController'            => __DIR__ . '/src/RcmRssFeed/Controller/ProxyController.php',
    'RcmRssFeed\Controller\PluginController'           => __DIR__ . '/src/RcmRssFeed/Controller/PluginController.php',
    'RcmRssFeed\Module'                                => __DIR__ . '/Module.php',
    'RcmRssFeed\Tests\Controller\PluginControllerTest' => __DIR__ . '/tests/src/RcmRssFeed/Controller/PluginControllerTest.php',
    'Bootstrap'                                        => __DIR__ . '/tests/Bootstrap.php',
);