<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmDoctrineJsonPluginStorage\Controller\BasePluginController'         => __DIR__ . '/src/RcmDoctrineJsonPluginStorage/Controller/BasePluginController.php',
    'RcmDoctrineJsonPluginStorage\Entity\InstanceConfig'                   => __DIR__ . '/src/RcmDoctrineJsonPluginStorage/Entity/InstanceConfig.php',
    'Bootstrap'                                                  => __DIR__ . '/test/Bootstrap.php',
    'RcmDoctrineJsonPluginStorageTest\Controller\BasePluginControllerTest' => __DIR__ . '/test/RcmDoctrineJsonPluginStorageTest/Controller/BasePluginControllerTest.php',
    'RcmDoctrineJsonPluginStorageTest\Entity\InstanceConfigTest'           => __DIR__ . '/test/RcmDoctrineJsonPluginStorageTest/Entity/InstanceConfigTest.php',
    'RcmDoctrineJsonPluginStorageTest\ModuleTest'                          => __DIR__ . '/test/RcmDoctrineJsonPluginStorageTest/ModuleTest.php',
    'RcmDoctrineJsonPluginStorage\Module'                                  => __DIR__ . '/Module.php',
);