<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RcmDoctrineJsonPluginStorage\Module' => __DIR__ . '/Module.php',
    'RcmDoctrineJsonPluginStorage\Controller\BasePluginController' => __DIR__
        . '/src/RcmDoctrineJsonPluginStorage/Controller/BasePluginController.php',
    'RcmDoctrineJsonPluginStorage\Entity\DoctrineJsonInstanceConfig' => __DIR__
        . '/src/RcmDoctrineJsonPluginStorage/Entity/DoctrineJsonInstanceConfig.php',
    'RcmDoctrineJsonPluginStorage\Model\InstanceConfigMerger' => __DIR__
        . '/src/RcmDoctrineJsonPluginStorage/Model/InstanceConfigMerger.php',
    'RcmDoctrineJsonPluginStorage\Repo\DoctrineJsonRepo' =>
        __DIR__ . '/src/RcmDoctrineJsonPluginStorage/Repo/DoctrineJsonRepo.php',
    'RcmDoctrineJsonPluginStorage\Repo\PluginStorageRepoInterface' => __DIR__
        . '/src/RcmDoctrineJsonPluginStorage/Repo/PluginStorageRepoInterface.php',
    'RcmDoctrineJsonPluginStorage\Service\PluginStorageMgr' => __DIR__
        . '/src/RcmDoctrineJsonPluginStorage/Service/PluginStorageMgr.php',
    'RcmDoctrineJsonPluginStorage\Service\PluginStorageMgrInterface' => __DIR__
        . '/src/RcmDoctrineJsonPluginStorage/Service/PluginStorageMgrInterface.php',
    'RcmDoctrineJsonPluginStorageTest\Controller\BasePluginControllerTest' =>
        __DIR__
        . '/test/RcmDoctrineJsonPluginStorageTest/Controller/BasePluginControllerTest.php',
    'RcmDoctrineJsonPluginStorageTest\Entity\InstanceConfigTest' => __DIR__
        . '/test/RcmDoctrineJsonPluginStorageTest/Entity/DoctrineJsonInstanceConfigTest.php',
    'RcmDoctrineJsonPluginStorage\Service\PluginStorageMgrMock' => __DIR__
        . '/test/RcmDoctrineJsonPluginStorageTest/Mock/PluginStorageMgrMock.php',
    'RcmDoctrineJsonPluginStorage\Repo\PluginStorageRepoMock' => __DIR__
        . '/test/RcmDoctrineJsonPluginStorageTest/Mock/PluginStorageRepoMock.php',
    'RcmDoctrineJsonPluginStorageTest\Entity\InstanceConfigMergerTest' =>
        __DIR__
        . '/test/RcmDoctrineJsonPluginStorageTest/Model/InstanceConfigMergerTest.php',
    'RcmDoctrineJsonPluginStorageTest\ModuleTest' =>
        __DIR__ . '/test/RcmDoctrineJsonPluginStorageTest/ModuleTest.php',
    'RcmDoctrineJsonPluginStorageTest\Entity\DoctrineJsonRepoTest' => __DIR__
        . '/test/RcmDoctrineJsonPluginStorageTest/Repo/DoctrineJsonRepoTest.php',
    'RcmDoctrineJsonPluginStorageTest\Entity\PluginStorageMgrTest' => __DIR__
        . '/test/RcmDoctrineJsonPluginStorageTest/Service/PluginStorageMgrTest.php',
);
