<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmDoctrineJsonPluginStorage\Entity\DoctrineJsonInstanceConfig'       => __DIR__ . '/src/RcmDoctrineJsonPluginStorage/Entity/DoctrineJsonInstanceConfig.php',
  'RcmDoctrineJsonPluginStorage\Controller\BasePluginController'         => __DIR__ . '/src/RcmDoctrineJsonPluginStorage/Controller/BasePluginController.php',
  'RcmDoctrineJsonPluginStorage\Storage\DoctrineJsonPluginStorage'       => __DIR__ . '/src/RcmDoctrineJsonPluginStorage/Storage/DoctrineJsonPluginStorage.php',
  'RcmDoctrineJsonPluginStorage\Service\PluginStorageMgr'          => __DIR__ . '/src/RcmDoctrineJsonPluginStorage/Service/PluginStorageMgr.php',
  'RcmDoctrineJsonPluginStorageTest\Entity\InstanceConfigTest'           => __DIR__ . '/test/RcmDoctrineJsonPluginStorageTest/Entity/DoctrineJsonInstanceConfigTest.php',
  'RcmDoctrineJsonPluginStorageTest\Controller\BasePluginControllerTest' => __DIR__ . '/test/RcmDoctrineJsonPluginStorageTest/Controller/BasePluginControllerTest.php',
  'RcmDoctrineJsonPluginStorageTest\ModuleTest'                          => __DIR__ . '/test/RcmDoctrineJsonPluginStorageTest/ModuleTest.php',
  'RcmDoctrineJsonPluginStorageTest\Mock\PluginStorageMock'              => __DIR__ . '/test/RcmDoctrineJsonPluginStorageTest/Mock/PluginStorageMock.php',
  'RcmDoctrineJsonPluginStorage\Module'                                  => __DIR__ . '/Module.php',
);
