<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmNumberFormat\Module' => __DIR__ . '/Module.php',
    'RcmNumberFormat\Controller\NumberFormatController' =>
        __DIR__ . '/src/RcmNumberFormat/Controller/NumberFormatController.php',
    'RcmNumberFormatTest\Controller\NumberFormatControllerTest' => __DIR__
        . '/test/RcmNumberFormatTest/Controller/NumberFormatControllerTest.php',
    'RcmNumberFormatTest\ModuleTest' =>
        __DIR__ . '/test/RcmNumberFormatTest/ModuleTest.php',
];
