<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmNumberFormat\Module'                            => __DIR__ . '/Module.php',
  'RcmNumberFormat\Controller\NumberFormatController' => __DIR__ . '/src/RcmNumberFormat/Controller/NumberFormatController.php',
);
