<?php

/**
 * RcmRotatingImage plugin template
 *
 * RcmRotatingImage plugin template
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   RcmPlugins\RcmRotatingImage
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-rotating-image/script.js',
    'text/javascript'
);
?>
<div>
    <a>
        <div class="images">
            <?php foreach($this->ic['images'] as $image){
                echo '<img style="display: none;" data-src="'.$image['src'].'" data-href="'.$image['href'].'" alt="'.$image['href'].'">';
            }?>
        </div>

        <div data-richEdit="learnMore" class="learnMore">
            <?=  $this->ic['learnMore'] ?>
        </div>
    </a>
</div>