<?php
/**
 * RcmRotatingImage plugin template
 *
 * RcmRotatingImage plugin template
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 */
$this->rcmIncludeJquery();
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-rotating-image/script.js',
    'text/javascript'
);
?>
<div>
    <a>
        <div class="images">
            <?php foreach ($instanceConfig['images'] as $image) {
                echo '<img style="display: none;" data-src="' . $image['src']
                    . '" data-href="' . $image['href'] . '" alt="'
                    . $image['href'] . '">';
            }?>
        </div>

        <?= $this->rcmRichEdit(
            'learnMore',
            '<h2>Learn More <span class=\"arrowLogo\">&nbsp;</span></h2>',
            'div',
            array('class' => 'learnMore')
        ) ?>
    </a>
</div>