<?php

/**
 * RcmRotatingImage plugin template
 *
 * RcmRotatingImage plugin template
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   RcmPlugins\RcmRotatingImage
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */
//$this->headLink()->appendStylesheet(
//    $this->basePath() . '/modules/rcm-rotating-image/style.css'
//);
?>
<div>
    <a href="<?php echo $this->image->href?>">
        <img src="<?php echo
            $this->getContentBasePath() . $this->image->src?>"
             alt="<?php echo $this->image->alt?>">

        <div data-textEdit="learnMore" class="learnMore">
            <?php echo $this->data->learnMore ?>
        </div>
    </a>
</div>