<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmPortalAnnouncementBox\Module' => __DIR__ . '/Module.php',
    'RcmPortalAnnouncementBox\Controller\PluginControllerTest' =>
        __DIR__ . '/tests/Controller/PluginControllerTest.php',
    'RcmPortalAnnouncementBox\Module\ModuleTest' =>
        __DIR__ . '/tests/Module/ModuleTest.php',
];
