<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmAngularJs\Module' => __DIR__ . '/Module.php',
    'RcmAngularJs\Factory\IncludeAngularJsViewHelperFactory' => __DIR__
        . '/src/RcmAngularJs/Factory/IncludeAngularJsViewHelperFactory.php',
    'RcmAngularJs\View\Helper\IncludeAngularJs' =>
        __DIR__ . '/src/RcmAngularJs/View/Helper/IncludeAngularJs.php',
];
