<?php
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-rss-feed/style.css'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-rss-feed/rssReader.js'
);
?>

<script type="text/javascript">
$(function(){
    $(".rss-feed-<?php echo $this->rcmPluginInstanceId; ?>");


    new rssReader(
        '<?php echo $this->rssProxy; ?>',
        <?php echo $this->rcmPluginInstanceId; ?>,
        $(".rss-feed-<?php echo $this->rcmPluginInstanceId; ?>"),
        null
    );
});
</script>

<div class="rcmRssFeedReaderMainContainer"
    data-rcmRssFeedUrl="<?php echo $this->data->rssFeedUrl; ?>"
    data-rcmRssFeedLimit="<?php echo $this->data->rssFeedLimit; ?>"
    data-rcmRssFeedProxy="<?php echo $this->rssProxy; ?>"
>

    <h2 data-textEdit="headline"><?php echo $this->data->headline; ?></h2>

    <span class="rss-feed-<?php echo $this->rcmPluginInstanceId; ?>">Loading...</span>
</div>
