<?php
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-rss-feed/style.css'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-rss-feed/RssReader.js'
);
?>

<script type="text/javascript">
$(function(){

    new RssReader(
        '<?php echo $this->rssProxy; ?>',
        <?php echo $this->instanceId; ?>,
        $(".rss-feed-<?php echo $this->instanceId; ?>"),
        null
    );
});
</script>

<div class="rcmRssFeedReaderMainContainer"
    data-rcmRssFeedUrl="<?php echo $this->ic['rssFeedUrl']; ?>"
    data-rcmRssFeedLimit="<?php echo $this->ic['rssFeedLimit']; ?>"
    data-rcmRssFeedProxy="<?php echo $this->rssProxy; ?>"
>

    <h2 data-textEdit="headline"><?php echo $this->ic['headline']; ?></h2>

    <span class="rss-feed-<?php echo $this->instanceId; ?>">Loading...</span>
</div>
