<script type="text/javascript">
    $(function () {

        new RssReader(
            '<?=  $this->rssProxy; ?>',
            <?=  $this->instanceId; ?>,
            $(".rss-feed-<?=  $this->instanceId; ?>"),
            null
        );
    });
</script>

<div class="rcmRssFeedReaderMainContainer"
     data-rcmRssFeedUrl="<?= $this->instanceConfig['rssFeedUrl']; ?>"
     data-rcmRssFeedLimit="<?= $this->instanceConfig['rssFeedLimit']; ?>"
     data-rcmRssFeedProxy="<?= $this->rssProxy; ?>"
    >

    <h2 data-textEdit="headline"><?= $this->instanceConfig['headline']; ?></h2>

    <span class="rss-feed-<?= $this->instanceId; ?>"></span>
</div>
