<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'RcmMockPlugin\Module' => __DIR__ . '/Module.php',
    'RcmMockPlugin\Controller\PluginController' =>
        __DIR__ . '/src/RcmMockPlugin/Controller/PluginController.php',
    'RcmMockPlugin\Exception\RuntimeException' =>
        __DIR__ . '/src/RcmMockPlugin/Exception/RuntimeException.php',
];
