<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmMessage\Module'                           => __DIR__ . '/Module.php',
  'RcmMessage\Controller\MessageListController' => __DIR__ . '/src/Controller/MessageListController.php',
  'RcmMessage\Entity\Destination'               => __DIR__ . '/src/Entity/Destination.php',
  'RcmMessage\Entity\Message'                   => __DIR__ . '/src/Entity/Message.php',
  'RcmMessage\View\Helper\RcmMessageIcon'       => __DIR__ . '/src/View/Helper/RcmMessageIcon.php',
);
