<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmMessage\Module'                                  => __DIR__ . '/Module.php',
  'RcmMessage\Controller\MessageListController'        => __DIR__ . '/src/Controller/MessageListController.php',
  'RcmMessage\Entity\Message'                          => __DIR__ . '/src/Entity/Message.php',
  'RcmMessage\Entity\UserMessage'                      => __DIR__ . '/src/Entity/UserMessage.php',
  'RcmMessage\Factory\RcmUserMessageListHelperFactory' => __DIR__ . '/src/Factory/RcmUserMessageListHelperFactory.php',
  'RcmMessage\Repository\Message'                      => __DIR__ . '/src/Repository/Message.php',
  'RcmMessage\Repository\UserMessage'                  => __DIR__ . '/src/Repository/UserMessage.php',
  'RcmMessage\View\Helper\RcmUserMessageListHelper'    => __DIR__ . '/src/View/Helper/RcmUserMessageListHelper.php',
);
