<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmPluginsCommon\Module'                              => __DIR__ . '/Module.php',
  'RcmPluginsCommon\Controller\EntityMgrAwareController' => __DIR__ . '/src/RcmPluginsCommon/Controller/EntityMgrAwareController.php',
  'RcmPluginsCommon\Controller\PluginProxyController'    => __DIR__ . '/src/RcmPluginsCommon/Controller/PluginProxyController.php',
);
