<!-- <rcmDialog> -->
<script type="text/ng-template" id="RcmStandardDialogTemplate">
    <div id="RcmStandardDialogTemplateIn" style="display: block;" ng-hide="loading">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">&times;</button>
                    <h1 class="modal-title"
                        id="myModalLabel">{{title}}</h1>
                </div>
                <div class="modal-body"><!-- CONTENT LOADED HERE -->
                </div>
                <div class="modal-footer">
                    <button
                        type="button"
                        class="btn btn-default"
                        data-dismiss="modal"
                        >
                        Close
                    </button>
                    <button type="button" class="btn btn-primary saveBtn">Save
                    </button>
                </div>
            </div>
        </div>
    </div>
</script>

<div class="modal fade"
     id="AdminDialogWindow"
     tabindex="-1"
     role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true"
     data-rcm-dialog="true"
    >
</div>
<!-- <rcmDialog/> -->