<script type="text/ng-template" id="RcmStandardDialogTemplate">
    <div id="RcmStandardDialogTemplateIn" style="display: block;" ng-hide="rcmAdminDialogState.loading">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">&times;</button>
                    <h1 class="modal-title"
                        id="myModalLabel">{{rcmAdminDialogState.title}}</h1>
                </div>
                <div class="modal-body" ng-include="content">
                </div>
                <div class="modal-footer">
                    <button
                        type="button"
                        class="btn btn-default"
                        data-dismiss="modal"
                        >
                        Close
                    </button>
                    <button type="button" class="btn btn-primary saveBtn">Save
                    </button>
                </div>
            </div>
        </div>
    </div>
</script>

<!--
<div id="RcmStandardDialogTemplateIn" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">&times;</button>
                <h1 class="modal-title" id="myModalLabel">Modal title</h1>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">Close
                </button>
                <button type="button" class="btn btn-primary saveBtn">Save
                </button>
            </div>
        </div>
    </div>
</div>
-->