<?php


$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-image-with-thumbnails/style.css'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-image-with-thumbnails/script.js'
);


?>

<div class="mainImage"><img src="<?= $this->instanceConfig[0]['main'] ?>"
                            class="imgClass"
                            border="0"/></div>

<ul class="imgThumbs">
    <?php $i = 0; ?>
    <?php foreach ($this->instanceConfig as $value) : ?>

        <li>
            <a href="#" rel="<?= $value['main']; ?>" class="image">
                <img src="<?= $value['thumb']; ?>"
                     class="thumb <?php if ($i == 0) {
                         echo "selected";
                     } ?>"
                     border="0"/>
            </a>
        </li>
        <?php $i++; ?>
    <?php endforeach; ?>

</ul>

