<?php


$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-image-with-thumbnails/style.css'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-image-with-thumbnails/script2.js'
);


?>

<div class="mainImage"><img src="<?php echo $this->data[0]->main?>" border="0"/></div>

<? foreach($this->data as $value) :?>

    <a href="#" rel="<?php echo $value->main; ?>" class="image">
        <img src="<?php echo $value->thumb; ?>" class="thumb" border="0" />
    </a>

<?php endforeach; ?>


<div class="clear"></div>

