<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'RcmInstanceConfig\Module'                                  => __DIR__ . '/Module.php',
  'RcmInstanceConfig\Controller\BasePluginController'         => __DIR__ . '/src/RcmInstanceConfig/Controller/BasePluginController.php',
  'RcmInstanceConfig\Entity\DoctrineJsonInstanceConfig'       => __DIR__ . '/src/RcmInstanceConfig/Entity/DoctrineJsonInstanceConfig.php',
  'RcmInstanceConfig\Model\InstanceConfigMerger'              => __DIR__ . '/src/RcmInstanceConfig/Model/InstanceConfigMerger.php',
  'RcmInstanceConfig\Repo\DoctrineJsonRepo'                   => __DIR__ . '/src/RcmInstanceConfig/Repo/DoctrineJsonRepo.php',
  'RcmInstanceConfig\Repo\PluginStorageRepoInterface'         => __DIR__ . '/src/RcmInstanceConfig/Repo/PluginStorageRepoInterface.php',
  'RcmInstanceConfig\Service\PluginStorageMgr'                => __DIR__ . '/src/RcmInstanceConfig/Service/PluginStorageMgr.php',
  'RcmInstanceConfig\Service\PluginStorageMgrInterface'       => __DIR__ . '/src/RcmInstanceConfig/Service/PluginStorageMgrInterface.php',
  'RcmInstanceConfigTest\Controller\BasePluginControllerTest' => __DIR__ . '/test/RcmInstanceConfig/Controller/BasePluginControllerTest.php',
  'RcmInstanceConfigTest\Entity\InstanceConfigTest'           => __DIR__ . '/test/RcmInstanceConfig/Entity/DoctrineJsonInstanceConfigTest.php',
  'RcmInstanceConfig\Service\PluginStorageMgrMock'            => __DIR__ . '/test/RcmInstanceConfig/Mock/PluginStorageMgrMock.php',
  'RcmInstanceConfig\Repo\PluginStorageRepoMock'              => __DIR__ . '/test/RcmInstanceConfig/Mock/PluginStorageRepoMock.php',
  'RcmInstanceConfigTest\Entity\InstanceConfigMergerTest'     => __DIR__ . '/test/RcmInstanceConfig/Model/InstanceConfigMergerTest.php',
  'RcmInstanceConfigTest\ModuleTest'                          => __DIR__ . '/test/RcmInstanceConfig/ModuleTest.php',
  'RcmInstanceConfigTest\Entity\DoctrineJsonRepoTest'         => __DIR__ . '/test/RcmInstanceConfig/Repo/DoctrineJsonRepoTest.php',
  'RcmInstanceConfigTest\Entity\PluginStorageMgrTest'         => __DIR__ . '/test/RcmInstanceConfig/Service/PluginStorageMgrTest.php',
);
