<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
  'RcmTinyMce\Module'                     => __DIR__ . '/Module.php',
  'RcmTinyMce\Controller\TestController'  => __DIR__ . '/src/RcmTinyMce/Controller/TestController.php',
  'RcmTinyMce\View\Helper\IncludeTinyMce' => __DIR__ . '/src/RcmTinyMce/View/Helper/IncludeTinyMce.php',
];
