<?php

$this->headLink()->appendStylesheet(
    $this->basePath()
    . '/modules/rcm-recommended-products/style.css'
);
?>
<div class="rcmRecommendedProductsList">
    <a href="<?= $this->escapeHtml($prodUrl) ?>">
    <div class="recommendedProductImage"><img
            src="<?= $this->escapeHtml($mainImage) ?>">
    </div>
    <div class="prodName">
        <?= $prodName ?>
    </div>
    <div class="orderNow">
        <button class="btn btn-primary">
            <?= $this->translate('Order Now') ?>
        </button>
    </a>
    </div>
</div>

