<?php

/**
 * RcmPortalAnnouncementBox content template
 *
 * Used for rendering simple content
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   http://www.nolicense.com None
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-portal-announcement-box/style.css'
);

?>
<div style="padding:5px;height:200px;width:200px;">
   <div data-textEdit="middle"
        style="position: relative; white-space: nowrap;height: 3px;width:200px; background-color: #f15d22; border: 0px; margin: 5px auto;color:#ffffff;font-weight: bold;text-align: center; vertical-align: middle; display: table-cell; verical-align: middle">
    <?php echo $this->data->middle?>
   </div>

    <p data-richEdit="html" style="width:200px; position: relative;">
        <?php echo $this->data->html ?>
    </p>


</div>
