<?php

/**
 * RcmPortalAnnouncementBox content template
 *
 * Renders this plugins view
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   http://www.nolicense.com None
 * @version   GIT: <git_id>
 */
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-portal-announcement-box/style.css'
);

?>
<div class="containerbox">
    <div data-textEdit="top" class="top">
        <?= $this->instanceConfig['top'] ?>
    </div>
    <div data-richEdit="html" class="bottom">
        <?= $this->instanceConfig['html'] ?>
    </div>
    <div class="linkStyle">
        <a href="<?= $this->instanceConfig['href'] ?>" class="urlContainer">
            <i>
                <div
                    data-textEdit="bottom"><?= $this->instanceConfig['bottom'] ?></div>
            </i>
        </a>
    </div>
</div>