<?php

/**
 * RcmPortalAnnouncementBox content template
 *
 * Used for rendering simple content
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Plugins\Image
 * @author    Rod McNew <rmcnew@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   http://www.nolicense.com None
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-portal-announcement-box/style.css'
);

?>
<div class="containerbox">
   <div data-textEdit="top" class="top">
    <?php echo $this->data->top?>
   </div>

    <div data-richEdit="html" class="bottom">
        <?php echo $this->data->html ?>
    </div>
    <p style="height: 7px; width:30px; position: absolute; bottom: 5px; right: 10px; color: black;border: 1px; padding: 5px; margin: 5px;">
    <a data-textEdit="href" href="<?php echo $this->data->href?>">
        <i><?php echo $this->data->href?></i>
    </a>
    </p>
</div>